Feature/to do test
CodeSoom/react-week3-assignment-1 pull request #47
Opened 2021-02-01 11:15 UTC by bluel00

1. 실패하는 테스트 작성
2. 최대한 빠르게 테스트 통과
3. 리팩토링

실패하는 테스트라는 것이 감이 좀 안잡힙니다.
일부러 틀린 값을 넣으면 될까요?

2021-02-01 12:14 UTC, bluel00 commented
할일 있을때 case 추가

2021-02-01 15:07 UTC, Kihyun92 commented
> 1. 실패하는 테스트 작성
> 2. 최대한 빠르게 테스트 통과
> 3. 리팩토링
> 
> 실패하는 테스트라는 것이 감이 좀 안잡힙니다.
> 일부러 틀린 값을 넣으면 될까요?

위 사이클은 TDD로 개발할 경우에 맞는 방식일 것 같아요. 아무것도 없는 상황에서 일단 테스트를 작성하는거죠. 그럼 실제 구현된 코드가 없기 때문에 해당 테스트는 실패할겁니다. 1번이 이 상황을 의미하는 것이고, 이미 구현된 로직에 테스트를 붙일때는 위와 같은 절차를 적용하기 쉽지 않겠죠.

2021-02-01 15:25 UTC, Kihyun92 requested changes
빠른 풀리퀘스트 좋습니다 👍🏼

2021-02-01 15:25 UTC, Kihyun92 commented on src/List.test.jsx
> +test('tasks 없을 때', () => {
좋습니다. 리스트가 비었을 경우와 비어있지 않는 경우에 대해서 각각 테스트 코드를 작성해보셨네요.

다만 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현해봐도 좋을 것 같아요 ㅎㅎ

``` jest
describe('List', () => {
  context('test의 length가 0인 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('test의 length가 1 이상인 경우', () => {
    ~~ 생략 ~~
```
일단 제 임의대로 작성해봤는데, 차례대로 보면 `List는 test의 length가 0인 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? :)

참고
- https://ko.javascript.info/testing-mocha
-  https://www.betterspecs.org/#contexts

2021-02-01 23:46 UTC, bluel00 commented on src/List.test.jsx
> +test('tasks 없을 때', () => {
앗 그렇군요. 
생각해보니 지금 과제는  코드가 다 구현된 상태에서 테스트를 작성하는 거니깐 TDD가 아니네요.
알려주신 구조로 케이스를 짜는데 더 집중해서 실습해보겠습니다. 🔍

2021-02-02 07:21 UTC, bluel00 commented
- describe context it 구조로 변경.

2021-02-02 12:38 UTC, Kihyun92 commented
> * describe context it 구조로 변경.

참고로 컨텍스트는

`with <-> without`

`when log in <-> when log out`

처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

2021-02-02 12:42 UTC, Kihyun92 requested changes

2021-02-02 12:42 UTC, Kihyun92 commented on src/List.test.jsx
> +      expect(getAllByTestId('todo-item').length).toEqual(2);
`toHaveLengthNumber()`를 사용할 수 있을까요?

- https://jestjs.io/docs/en/expect#tohavelengthnumber

2021-02-02 12:42 UTC, Kihyun92 commented on src/List.test.jsx
> +      ));
매 테스트마다 리스트 컴포넌트를 렌더하기 위해 중복 코드가 발생하는 것 같아요.

공통 함수를 it 바깥으로 분리하면 어떤가요?

2021-02-03 11:35 UTC, bluel00 commented on src/List.test.jsx
> +      expect(getAllByTestId('todo-item').length).toEqual(2);
네 수정했습니다.

2021-02-03 11:35 UTC, bluel00 commented on src/List.test.jsx
> +      ));
네 함수로 추출했습니다.

2021-02-03 11:39 UTC, bluel00 commented
중복코드 render 함수 추출
요소 개수 체크 .toHaveLength(number) 로 변경

2021-02-03 13:20 UTC, Kihyun92 requested changes
잘 진행하고 계시네요 ㅎㅎ

테스트 코드도 리팩터링 대상입니다. 불필요한 로직이나 개선점은 없는지 지속적으로 확인해주세요~

2021-02-03 13:20 UTC, Kihyun92 commented on src/Input.test.jsx
> +  function myRender({ taskTitle, onChangeTitle, onClickAddTask }) {
`myRender`라는 함수명 보다는 `renderInput`과 같이 조금 더 명확히 나타내는건 어떤가요?

2021-02-03 13:20 UTC, Kihyun92 commented on src/Input.test.jsx
> +    const onClickAddTask = jest.fn();
이 부분도 중복되는 것 같아요~

2021-02-03 13:20 UTC, Kihyun92 commented on src/Input.test.jsx
> +  it('input 값 입력', () => {
스트하는 대상이 실제로 어떤 일을하고 어떤 변화가 일어나는지를 중심적으로 적으면 의도가 더 잘 드러날 것 같아요.
`input의 값을 변경하면 input의 값이 변경된다`는 어떨까요?

2021-02-03 13:20 UTC, Kihyun92 commented on src/List.test.jsx
> +      const { container } = myRender({});
이렇게만 처리해도 될 것 같네요.
```suggestion
      const { container } = myRender();
```

2021-02-03 13:20 UTC, Kihyun92 commented on src/Page.test.jsx
> +    },
파라미터가 이렇게 많이 필요한 이유가 있나요?

지금 테스트를 하는데 불필요한 파라미터는 없을까요?

2021-02-03 13:20 UTC, Kihyun92 commented on src/Page.test.jsx
> +    it('UI 모두 표시한다.', () => {
UI라는 말은 해석하기에 따라 범위가 굉장히 차이날 것 같아요. 

조금 더 명확하게 적어주면 좋을 것 같습니다~

2021-02-04 05:17 UTC, bluel00 commented
1. App.test.jsx 추가
2. 리펙터링
- 중복코드 제거
- 필요한 파라미터만 남기고 제거
- 함수명 명확하게 변경
- 테스트 설명 명확하게 작성

2021-02-04 13:26 UTC, Kihyun92 requested changes
잘 진행해주고 계신것 같습니다 👍🏼

2021-02-04 13:26 UTC, Kihyun92 commented on src/Input.test.jsx
> +  it('input의 값을 변경하면 input의 값이 변경된다', () => {
`handleChange`가 호출되는지 확인해봐도 좋을 것 같네요~

2021-02-04 13:26 UTC, Kihyun92 commented on src/List.test.jsx
> +      expect(container).toHaveTextContent('운동하기');
지금은 확인하는 task가 두개밖에 없지만, task를 추가로 확인해야하는 경우엔 계속 하단에 같은 로직을 추가해야할 것 같군요.

다시말해 tasks를 이용해 반복되는 로직을 처리할 방법이 있을까요?

2021-02-05 06:52 UTC, bluel00 commented on src/List.test.jsx
> +      expect(container).toHaveTextContent('운동하기');
네 forEach로 처리했습니다.

2021-02-05 06:54 UTC, bluel00 commented
- 함수 호출되는지 확인
- 반복되는 로직 forEach로 변경

2021-02-05 13:55 UTC, Kihyun92 requested changes
잘 진행하고 계신 것 같아요 좋습니다 :)

아마 마지막 리뷰가 될 것 같아요.

테스트 코드 또한 리팩터링의 대상입니다. 지속적으로 불필요한 로직은 없는지, 개선할 방법이 있는지 고민해보시면 좋을 것 같습니다 ☺️

2021-02-05 13:55 UTC, Kihyun92 commented on src/Page.test.jsx
> +        ...defaultParameter,
매 테스트마다 `taskTitle`은 빈값으로 들어가는 것 같아요.

renderPage 함수에서 taskTitle을 인자로 받아야할까요?

이 경우 defaultParameter로 처리할 필요가 없을 것 같아요

2021-02-06 01:37 UTC, bluel00 commented
- 안쓰는 파라미터 제거
- 할일 목록 확인하는 부분 forEach로 처리

2021-02-06 01:38 UTC, bluel00 commented on src/Page.test.jsx
> +        ...defaultParameter,
말씀대로 매번 받을 필요없군요.
수정했습니다.

2021-02-06 13:15 UTC, Kihyun92 approved these changes
고생하셨습니다~ 리뷰 드린것보다 더 잘 반영해주신 것 같아요 😁

과제 풀이 영상을 꼭 보시고, 아샬님은 어떻게 테스트를 접근하시는지 보시면 좋겠습니다~

회고 올려주시면 머지하도록 하겠습니다ㅎㅎ

2021-02-06 13:15 UTC, Kihyun92 commented on src/App.test.jsx
> +    });
이 부분은 이렇게만 처리해도 될 것 같네요~
```suggestion
    } = renderApp();
```

2021-02-06 13:15 UTC, Kihyun92 commented on src/Page.test.jsx
> +  ) {
인자가 하나밖에 없을땐 줄바꿈을 굳이 안해줘도 될 것 같아요~ 그리고 객체로 받을 필요도 없을 것 같구요.
```suggestion
  function renderPage(tasks) {
```

2021-02-07 04:20 UTC, bluel00 commented
- 코드정리를 했습니다.


3주차 회고입니다. 

https://www.notion.so/3-ab21e3046b984932acdeeee77a7dfa0d

2021-02-07 12:43 UTC, merged