To-do List Test 작성해보기
CodeSoom/react-week3-assignment-1 pull request #48
Opened 2021-02-01 11:34 UTC by shinhyogeun

후...너무 어렵네요.😭😭😭

일단은 List에 관한 test를 만들어봐서 PR을 보냅니다! 지금은 Input에 대해서 만들고 있는데 List에 관해서 만든 것도 이게 제대로 만든건지 감이 잡히지 않습니다..ㅠㅠ 나름대로 말씀 드리면 일단은 **List에서는 완료버튼을 Test하지 않았습니다.** 그 이유는 Item에서 완료버튼을 눌렀을 때를 test를 이미 했기 때문에 List는 
**1. 여러가지 할 일들이 출력이 잘 나오는지** 
**2. 할 일이 아무것도 없을 때는 할 일이 없다는 출력이 잘 나오는지**
를 확인 하는 것에 집중했습니다.

2021-02-01 11:52 UTC, shinhyogeun commented
Input.test.jsx에서 왜  `expect(input).toHaveAttribute('value', '누워있기');` 이 부분이 실패하는지 모르겠습니다.. 🤔🤔
구글링을 많이 해봤는데 input의 value가 바뀌지 않는것 같습니다. 혹시 제가 잘못 사용하는 부분이 있을까요?
그리고 커밋은 Fail - Pass - Refactor 단계로 하는 것이 좋을까요?

2021-02-01 14:58 UTC, Kihyun92 requested changes
빠른 PR 좋습니다 👍🏼

2021-02-01 14:58 UTC, Kihyun92 commented on src/List.test.jsx
> +test('When List have several Task', () => {
오 좋습니다. 리스트가 비었을 경우와 비어있지 않는 경우에 대해서 각각 테스트 코드를 작성해보셨네요.

추가적으로 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현해보는 건 어떤가요?

``` jest
describe('List', () => {
  context('test의 length가 0인 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('test의 length가 1 이상인 경우', () => {
    ~~ 생략 ~~
```
일단 제 임의대로 작성해봤는데, 차례대로 보면 `List는 test의 length가 0인 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? :)

참고
- https://ko.javascript.info/testing-mocha
-  https://www.betterspecs.org/#contexts

2021-02-01 14:58 UTC, Kihyun92 commented on src/List.test.jsx
> +  ));
테스트마다 같은 처리를 해주고 있는 것 같아요. 중복을 없앨 순 없을까요?

2021-02-01 14:58 UTC, Kihyun92 commented on src/Input.test.jsx
> +    expect(input).toHaveAttribute('value', '누워있기');
value가 변경되는지를 테스트해보려는 의도 같네요.

`expect(handleChange).toBeCalled();`

이런 방법은 어떤가요? 핸들러 호출 여부만 신경 쓰는 거죠.ㅎㅎ

버튼 클릭 후 일어나는 일보단 버튼이 제대로 동작했는지만 신경 쓰는 겁니다.

어떤 장점이 있을까요?

2021-02-01 15:03 UTC, Kihyun92 commented on src/Input.test.jsx
> +  it('If Input change then onChange function occur?', () => {
테스트를 일종의 사용설명서라고 보면 좋을 것 같아요. 동료들이 실제 로직을 보지않고도 해당 컴포넌트의 동작을 이해 할 수 있도록요.

위와 같은 문장보다는, `인풋은 변경이 됐을때, ~~한다`와 같은 문장은 어떤가요?

2021-02-01 15:25 UTC, shinhyogeun commented on src/Input.test.jsx
> +    expect(input).toHaveAttribute('value', '누워있기');
제가 최종적으로 확인하고 싶은 것은 정말 `expect(handleChange).toBeCalled();` 이게 정확한 것 같아요! input이 입력이 된다면 onClick이 실행되는지 안되는지가 정확한거죠! 물론 그 후의 setState가 실행되고 다시 그려지는 것은 이 Input Component가 신경쓸 부분이 아니라고 생각합니다!  **(장점이라고 한다면 관심사가 더욱 분리되고 현상에 집중한다고 말씀드릴 수 있을까요?)**
그리고 `expect(input).toHaveAttribute('value', '누워있기');`이 통과하지 못하는 이유는 value는 Input의 props에서 오는 것이고 제가 
value을 중간에서 강제로 수정해서 그런건가요? 다시 말씀드리면
(input에서 키보드를 누르면 -> onClick실행 -> 다시 InputComponent 그리기(여기서 새로운 value가 옴) 이 순서에서 제가 강제로 vlaue를 수정하려고 한 건가요?
워낙 tdd가 어려워서 생각하나하나가 어렵고 조심스러워지네요..🤔그래도 재밌습니다~!😊

2021-02-02 10:04 UTC, shinhyogeun commented on src/List.test.jsx
> +test('When List have several Task', () => {
`describe - context - it`구조로 모두 바꾸었습니다~!! 확실히 깔끔하게 읽히는 것 같네요!!👍

2021-02-02 10:05 UTC, shinhyogeun commented on src/List.test.jsx
> +  ));
함수로 바깥으로 빼서 처리했습니다!!

2021-02-02 10:05 UTC, shinhyogeun commented on src/Input.test.jsx
> +  it('If Input change then onChange function occur?', () => {
조금 더 명확하게 다시 작성하였습니다!!

2021-02-02 10:09 UTC, shinhyogeun commented
테스트의 깊이에 대해서 꼭 드리고 싶은 질문이 있습니다.🤔
테스트는 가능한 범위에서는 다양한 시도를 할 수 있는 것같습니다. 물론 Coverage를 보장해야 한다는 것을 만족 한다면요!
그런데 꼭 해야하는 테스트지만 어떻게 가능한지 감이 잡히지 않는 부분이 있습니다. 또한 이것이 테스트를 해야하는 것인지도 헷갈립니다.

**1. List.jsx에서 List의 완료버튼을 누르면 그 줄이 잘 삭제가 되는지를 테스트해야 할까?**

List를 Test할 때 List의 완료버튼을 누르면 그 줄이 잘 삭제가 되는지는 정말 중요한 기능입니다. 하지만 정확하게는 삭제라는 기능은 없는 것 같습니다. 그건 App.js에서 setState로 상태를 변경시키고 다시 그리는 것일 뿐입니다. List에서는 각각의 Task를 삭제할 책임은 없습니다. 단지 onClick을 실행시킬 책임만 있다고 생각합니다. 그래서 저는 완료버튼을 누르면 그 줄이 삭제가 되는지를 test하지 않았고 저의 생각이 틀려서 해야한다고해도..ㅠㅠ 어떻게 해야할지 모르겠습니다. 

**2. Input.jsx에서 input에 변경이 일어나면 input의 value가 바뀐다는 것이 테스트가능한가요?**

1번의 질문과 비슷한 질문입니다. 저는 Input에 변경이 일어나면 setState가 실행되고 다시 Input Component가 그려지면서 새로운 value가 할당된다고 생각했습니다. 그렇지만 Input을 테스트할 때 테스트 파일 안에서는 setState함수도 모르고 다시 그려진다는 사실도 알 수 없습니다. 그러면 input의 value가 바뀐다는 것이 test할 수 없는 것 아닌가요?

**3. Page.jsx에서의 test는 중복이 가득할것 같습니다.**

Page는 오로지 Input과 List로만 이루어져 있습니다. 그래서 Page에서의 test는 Input과 List들에서의 test와 중복이 많이 있습니다. 이것은 잘못된 방향인가요??

감사합니다!👍👍

2021-02-02 12:43 UTC, Kihyun92 commented on src/List.test.jsx
> +test('When List have several Task', () => {
참고로 `context`는

`with <-> without`

`when log in <-> when log out`

처럼 같은 맥락에서 별개의 사례일 때 사용합니다.

2021-02-02 13:21 UTC, Kihyun92 commented
> 테스트의 깊이에 대해서 꼭 드리고 싶은 질문이 있습니다.🤔
> 테스트는 가능한 범위에서는 다양한 시도를 할 수 있는 것같습니다. 물론 Coverage를 보장해야 한다는 것을 만족 한다면요!
> 그런데 꼭 해야하는 테스트지만 어떻게 가능한지 감이 잡히지 않는 부분이 있습니다. 또한 이것이 테스트를 해야하는 것인지도 헷갈립니다.
> 
> **1. List.jsx에서 List의 완료버튼을 누르면 그 줄이 잘 삭제가 되는지를 테스트해야 할까?**
> 
> List를 Test할 때 List의 완료버튼을 누르면 그 줄이 잘 삭제가 되는지는 정말 중요한 기능입니다. 하지만 정확하게는 삭제라는 기능은 없는 것 같습니다. 그건 App.js에서 setState로 상태를 변경시키고 다시 그리는 것일 뿐입니다. List에서는 각각의 Task를 삭제할 책임은 없습니다. 단지 onClick을 실행시킬 책임만 있다고 생각합니다. 그래서 저는 완료버튼을 누르면 그 줄이 삭제가 되는지를 test하지 않았고 저의 생각이 틀려서 해야한다고해도..ㅠㅠ 어떻게 해야할지 모르겠습니다.
> 
> **2. Input.jsx에서 input에 변경이 일어나면 input의 value가 바뀐다는 것이 테스트가능한가요?**
> 
> 1번의 질문과 비슷한 질문입니다. 저는 Input에 변경이 일어나면 setState가 실행되고 다시 Input Component가 그려지면서 새로운 value가 할당된다고 생각했습니다. 그렇지만 Input을 테스트할 때 테스트 파일 안에서는 setState함수도 모르고 다시 그려진다는 사실도 알 수 없습니다. 그러면 input의 value가 바뀐다는 것이 test할 수 없는 것 아닌가요?
> 
> **3. Page.jsx에서의 test는 중복이 가득할것 같습니다.**
> 
> Page는 오로지 Input과 List로만 이루어져 있습니다. 그래서 Page에서의 test는 Input과 List들에서의 test와 중복이 많이 있습니다. 이것은 잘못된 방향인가요??
> 
> **4. input의 value가 바뀌지 않는 이유**
> [#48 (comment)](https://github.com/CodeSoom/react-week3-assignment-1/pull/48#issuecomment-770800433)
> 위의 질문에 대해서 제가 답을 찾아봤는데 `expect(input).toHaveAttribute('value', '누워있기');`이 통과하지 못하는 이유는 value는 Input의 props에서 오는 것이고 제가 value을 중간에서 강제로 수정해서 그런건가요? 다시 말씀드리면 (input에서 키보드를 누르면 -> onClick실행 -> 다시 InputComponent 그리기(여기서 새로운 value가 옴) 이 순서에서 제가 강제로 vlaue를 수정하려고 한 건가요?
> 
> 감사합니다!👍👍

테스트를 작성해보시면서 많은 고민을 해보고 계신것 같습니다 ㅎㅎ

테스트에서 중요한 부분은 `내가 얼마나 안심할 수 있는가`인 것 같아요. 그러다보면 어느정도 중복이 발생할 수 있겠죠.

각 컴포넌트마다 가지고 있는 관심사의 수준이 다르기 때문에 하위 컴포넌트의 구현 상세를 과도하게 테스트하게 될 수 있습니다. 이 경우 상위에서 너무 많은 걸 알고 있다는 신호고 이는 설계적으로 문제가 될 수 있습니다.

그러나 이 부분에 대해서 지금 너무 깊게 고민하지 않으셨으면 해요. 경험치가 누적되지 않으면 사실 판단하기 어렵습니다. 그래서 훈련할 땐 극단적으로 테스트를 작성하는 걸 권합니다. 그래야 적정 수준의 테스트가 무엇인지 알 수 있게 됩니다. 지금은 떠오르는 불안들은 잠시 넣어두시고, 테스트 커버리지 100프로에 대한 집착만 남겨둬 보셔요 😁

2번과 같은 경우엔 어떻게하면 깔끔하게 Input과 같은 컴포넌트의 역할을 드러낼 수 있는지 고민해보시고 사용 설명서로서 테스트 코드를 생각하시면 좋을 것 같습니다.

해당 컴포넌트를 사용하는 사람들에게 예제로 테스트를 제공하는거죠. 무엇을 어떻게 보여주는게 좋을지 고민해보시고 적용해보세요 ㅎㅎ

4번은 맞게 이해하신 것 같습니다 ㅎㅎ

2021-02-02 13:31 UTC, Kihyun92 requested changes
제가 드리는 리뷰보다 더 잘 반영해주시는 것 같아요! 좋습니다 💯

2021-02-02 13:31 UTC, Kihyun92 commented on src/Input.test.jsx
> +function showInputWith(value, handleChange = onChange, handleClick = onClick) {
조금 더 명확하게`renderInputWith`이나 `renderInput`은 어떤가요? ㅎㅎ

2021-02-02 13:31 UTC, Kihyun92 commented on src/Page.test.jsx
> +  handleClickDeleteTask = onClickDeleteTask,
default값을 처리해준게 좋네요! 다만 지금 테스트에서 뭔가 새로운 핸들러가 추가될 일이 있나요? 
없다면 아래 페이지 컴포넌트에 바로 넘겨주는것도 좋을것 같네요 ㅎㅎ

2021-02-02 13:31 UTC, Kihyun92 commented on src/List.test.jsx
> +}
그리고 다른 `describe`가 추가될 경우도 있으니 `describe` 안에 작성해도 괜찮을 것 같군요.

2021-02-03 05:55 UTC, shinhyogeun commented on src/Input.test.jsx
> +function showInputWith(value, handleChange = onChange, handleClick = onClick) {
show보다는 render가 더 명확한 것 같습니다! 네 반영하겠습니다!👍

2021-02-03 05:56 UTC, shinhyogeun commented on src/Page.test.jsx
> +  handleClickDeleteTask = onClickDeleteTask,
오.. 보고 놀랐습니다.. 네 바로 바꾸겠습니다!!

2021-02-03 07:57 UTC, shinhyogeun commented on src/List.test.jsx
> +}
네 수정했습니다!😊

2021-02-03 08:01 UTC, shinhyogeun commented
App.jsx을 테스트하면서 input의 value가 update되고 list가 추가되고 삭제되는 것, 다시그려지는 것의 test를 여기서 해야한다는 것을 알았습니다. 처음에 App에서 상태를 관리하게 만들었으니 App에서는 상태가 잘변화가 되고 다시 잘그려지는 지 확인해야 합니다. 그에 비해 이 밑에 있는 component들은 각자 자기에게 인자를 주어졌을 때 보여주고 함수를 실행하는 그 이상의 것은 거기서 테스트 할 수 없었습니다. 관심사를 확실히 분리해서 그랬던 것 같습니다.🤔

2021-02-03 13:46 UTC, Kihyun92 requested changes
잘 진행하고 계신 것 같습니다 👍🏼 

사용 설명서 측면에서 무엇을 보여주고 싶은지 고민해보시고 테스트를 작성해보시는 것도 도움이 될 것 같아요~

2021-02-03 13:46 UTC, Kihyun92 commented on src/App.test.jsx
> +    fireEvent.change(getByPlaceholderText('할 일을 입력해 주세요'), { target: { value: '누워있기' } });
줄바꿈을해주면 가독성이 더 좋아질 것 같아요~

2021-02-03 13:46 UTC, Kihyun92 commented on src/Page.test.jsx
> +  const onClickDeleteTask = jest.fn();
mock 함수들은 초기화해주지 않으면 테스트가 올바르게 동작하지 않을 수 있습니다. 위에서 이미 `onClickAddTask `가 호출되었을 때 다른 테스트에서 `onClickAddTask `가 호출되었는지 확인할 경우가 올바르게 테스트가 동작하지 않을 수 있습니다.

```js
beforeEach(() => {
  jest.clearAllMocks();
});
```
See also
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks
  - https://jestjs.io/docs/en/setup-teardown

2021-02-03 13:46 UTC, Kihyun92 commented on src/List.test.jsx
> +  context('tasks에 할 일이 하나도 없을 때', () => {
`tasks가 없을때` 혹은 `할 일이 없을때` 라고만 해도 되지 않을까요?

tasks가 결국 할일 이니까요 ㅎㅎ

2021-02-03 13:46 UTC, Kihyun92 commented on src/List.test.jsx
> +  context('tasks에 여러가지 할 일들이 있을 때', () => {
이 부분은 `할 일(혹은 tasks)가 있을때` 는 어떤가요?

2021-02-04 04:20 UTC, shinhyogeun commented on src/App.test.jsx
> +    fireEvent.change(getByPlaceholderText('할 일을 입력해 주세요'), { target: { value: '누워있기' } });
네 정리하겠습니다~!

2021-02-04 04:22 UTC, shinhyogeun commented on src/Page.test.jsx
> +  const onClickDeleteTask = jest.fn();
넵 수정하겠습니다!👍

2021-02-04 04:24 UTC, shinhyogeun commented on src/List.test.jsx
> +  context('tasks에 할 일이 하나도 없을 때', () => {
테스트 이름 붙이는게 어렵네요..ㅠㅠ 네 바꾸겠습니다!!

2021-02-04 04:24 UTC, shinhyogeun commented on src/List.test.jsx
> +  context('tasks에 여러가지 할 일들이 있을 때', () => {
위와 맞춰서 바꾸겠습니다🤔

2021-02-04 04:45 UTC, shinhyogeun commented
**App.jsx**

주된 관심사 : 상태를 변경하고 그에 따라 다시 그린다.
- test 1 : Input을 입력하면 Input이 변경된다.
- test 2 : 추가버튼을 클릭하면 Input은 비워지고 list에 추가된다.
- test 3 : 완료버튼을 클릭하면 list에서 사라진다.

**Input.jsx**

주된 관심사 : input과 button을 그려준다.
- test 1 : 입력란(input)과 추가버튼(button)을 보여준다.
- test 2 : 인풋에 변경이 일어나면 onChange함수가 실행된다.
- test 3 : 추가버튼을 클릭하면 onClick함수가 실행된다

**List.jsx**

주된 관심사 : Item들을 그려준다.
- test 1 : tasks가 있을 때 그 일들을 모두 보여준다.
- test 2 : tasks가 있을 때 완료버튼을 누르면 onClickDelete 함수를 실행한다.
- test 3 : tasks가 없을 때 할 일이 없다는 것을 보여준다.

**Page.jsx**

주된 관심사 : Input과 List를 그려준다.
- test 1 : tasks가 있을 때 Input과 List를 보여준다.
- test 2 : tasks가 있을 때 추가버튼을 누르면 onClickAddTesk함수가 실행된다.
- test 3 : tasks가 있을 때 완료버튼을 누르면 onClickDelete 함수를 실행한다.
- test 4 : tasks가 없을 때 인풋과 할 일이 없다는 것을 보여준다.
- test 5 : tasks가 없을 때 추가버튼을 누르면 onClickAddTesk함수가 실행된다.
---------------------------------------------------------------------------------
위에는 제가 test한 코드들을 정리한 것입니다. 여기서 궁금한 것이 있습니다!!

**1. 하위 컴포넌트가 있는지 확인하는 방법은 오로지 button,input,list 이렇게 알려진 tag들로만 가능한가요?**
예를 들면 Page의 test1에서 Input 컴포넌트가 화면에 있는지 확인을 할 때 저는 Input컴포넌트안에 있는 input과 button이 Page속에 있는지 확인합니다.
이 방법이 틀린 것은 아니지만 Input컴포넌트가 복잡해지면 많이 힘들어질 것 같습니다. Page컴포넌트에서 Input컴포넌트가 잘 그려졌는지 깔끔하게 확인할 수 있는 방법은 없을까요?

**2. test하는 것 꼭 영어로 써야하나요?**
하하하… 다른 분들은 영어로 쓰시던데  영어로 작성해야 하는 습관이 좋은건가요?  트레이너님의 의견이 궁금합니다!🤔(현업에서는 어떻게 사용하시는지도 궁금합니다!)

2021-02-05 10:49 UTC, Kihyun92 commented
> 1. 하위 컴포넌트가 있는지 확인하는 방법은 오로지 button,input,list 이렇게 알려진 tag들로만 가능한가요?


일단 제가 아는 방법으로는 없는 것 같아요.. ㅎㅎ input 컴포넌트가 복잡해지는게 어떤 경우일까요? 여러 인풋들이 있는 경우라면 모든 인풋과 버튼들을 모두 받아와서([getAllBy*](https://testing-library.com/docs/queries/about#types-of-queries)) 반복문으로 확인 할 수 있을 것 같아요.

> 2. test하는 것 꼭 영어로 써야하나요?

팀에서 정하기에 따라 다른 것 같아요. 지금 회사는 영어로 작성하고있고, 이전 회사는 한글로도 했었습니다 ㅎㅎ 
개인적으로는 영어로 작성해도 의도를 명확히 나타낼 수 있다면 영어로 작성해주는게 좋은 것 같습니다만, 일단은 본인이 편한대로 테스트를 작성해보는게 좋을 것 같아요~

> 3. 추가로 테스트하면 좋을 (혹은 삭제할) 것이 있을까요?

이번 과제에 답은 없습니다 ㅎㅎ 
테스트를 일종의 사용설명서라고 생각해보시면 좋을 것 같아요. 해당 컴포넌트를 사용하는 사람에게 예제로 테스트를 제공하는거죠.
무엇을 보여주고 싶으신가요?

2021-02-05 15:37 UTC, Kihyun92 requested changes

2021-02-05 15:37 UTC, Kihyun92 commented on src/Page.test.jsx
> +    tasks = '',
```suggestion
    tasks = [],
```
tasks는 배열이어야 하지 않나요?

2021-02-05 15:37 UTC, Kihyun92 commented on src/Page.test.jsx
> +      expect(getByPlaceholderText('할 일을 입력해 주세요')).toHaveValue(taskTitle);
두개 다 확인이 필요할까요? 아래 테스트만 확인해도 되지 않을까요?

2021-02-06 10:04 UTC, shinhyogeun commented on src/Page.test.jsx
> +      expect(getByPlaceholderText('할 일을 입력해 주세요')).toHaveValue(taskTitle);
이것에 대해서 슬랙에서 이야기를 나눴는데 밑에 것이 위에 것도 포함한다고 생각합니다! 네 아래 테스트만 살리도록 하겠습니다~!👍

2021-02-06 10:04 UTC, shinhyogeun commented on src/Page.test.jsx
> +    tasks = '',
그렇습니다! 기본값을 사용할 경우가 없어서 몰랐습니다! 바로 수정하겠습니다!😊

2021-02-06 10:09 UTC, shinhyogeun commented
제가 사용자에게 보여주고 싶은 것은 크게 보면 제가 만든 **화면 + 동작**입니다. 화면이 잘 나오는지는 App.js가 아닌 파일들의 test에서 확인했습니다. 그리고 동작은 App.js에서 test를 했습니다. 이렇게 두 개로 관심사가 분리되니 test도 분리가 잘 된 것 같았습니다! 하지만 test가 개발을 주도한다는 느낌은 아직 잘 모르겠습니다 ㅠㅠ 이것은 만들어 진 것에 test를 붙이는 과정이어서 그랬던 것 같습니다. **다음주부터 TDD를 하게 되면 정말 test가 개발을 주도한다는 느낌을 느낄 수 있을 것 같습니다!**

2021-02-06 12:53 UTC, Kihyun92 approved these changes
고생하셨습니다~ 벌써 다음 TDD가 기대된다고 하시니 좋네요 👍🏼 

앞으로 모든 과제는 TDD로 진행하실거라 이 부분은 천천히 익혀가시면 될 것 같습니다 ㅎㅎ

과제 풀이 영상을 꼭 보시고, 아샬님은 어떻게 테스트를 접근하시는지 보시면 좋겠습니다~

회고 올려주시면 머지할게요 😁

2021-02-07 12:38 UTC, merged