To-do app 테스트케이스 작성
CodeSoom/react-week3-assignment-1 pull request #51
Opened 2021-02-01 18:25 UTC by SangHoonly

첫번째로, List.test.jsx를 작성하였습니다.
tasks가 빈 array의 경우, '할 일이 없어요'가 뜨면 잘 동작하는 것으로 케이스를 두었고,
tasks에 task가 있을 시 보여주는 케이스는 Input 컴포넌트에서 추가 버튼을 눌렀을 때 제대로 동작하는 경우와 겹친다고 판단하여, 구현하지 않았습니다.

2021-02-02 09:54 UTC, SangHoonly commented
Page.test.jsx에서 test가 동작하는 방식이, input에 값을 넣고 추가 버튼을 클릭하면 리스트에서 값의 반영 여부를 체크하는 식으로 하려 했는데 값이 업데이트가 안되네요. Item.test.jsx에서 버튼을 누르면 할일이 삭제 되는 것과 같은 방식으로 했는데 왜 반영이 안되는지는 잘 모르겠습니다. 버튼마저 차별하는 세상...

2021-02-03 12:01 UTC, SangHoonly commented
생각해보니, tasks에 할 일이 추가되지 않아 생겼던 문제였던 것 같습니다. 그래서 tasks에 할 일을 추가하고 리렌더링을 시켜주어, 테스트가 제대로 동작하는지 확인하였습니다.

2021-02-03 12:36 UTC, SangHoonly commented
state선언과 구성은 App 컴포넌트, Page에서는 넘겨받은 state를 바탕으로 화면에 어떻게 보일 것인지 처리를 하는데, 고민을 해 본 결과 사실 이 두 개를 완전히 분리할 수 없어 달라지는 state를 바탕으로 여러 테스트를 진행하는 것을 Page에 위임하고, App의 테스트에서는 간단하게 랜더링 되는지만 평가하는 것이 좋을 것 같다는 생각이 들었습니다. 추후 코드의 방향은 그렇게 잡겠습니다.

2021-02-03 13:18 UTC, SangHoonly commented
![스크린샷 2021-02-03 오후 10 17 35](https://user-images.githubusercontent.com/54464320/106752309-a45da100-666d-11eb-945b-3aeec8bd80a2.png)

위의 Stmts, Funcs, Lines는 각각 무엇이며 왜 통과가 안되는 거죠...??

2021-02-03 14:39 UTC, Kihyun92 commented
상훈님 리뷰가 늦었습니다. 죄송합니다..

혹시나 리뷰가 하루 이상 늦어진다면 트레이너들에게 DM으로 말씀해주시면 감사하겠습니다 🙇🏻‍♂️

2021-02-03 14:54 UTC, Kihyun92 requested changes

2021-02-03 14:54 UTC, Kihyun92 commented on src/List.test.jsx
> +test('emptyList', () => {
할일이 없을때와 있을때를 구분해서 테스트 코드를 작성해보셨네요~

`describe - context - it`의 구조를 사용한다면 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해줄 수 있을 것 같아요

``` jest
describe('List', () => {
  context('test의 length가 0인 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('test의 length가 1 이상인 경우', () => {
    ~~ 생략 ~~
```
일단 제 임의대로 작성해봤습니다.(영어로 하셔도 됩니다)

차례대로 보면 `List는 test의 length가 0인 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요?☺️

참고
- https://ko.javascript.info/testing-mocha
- https://www.betterspecs.org/#contexts

2021-02-03 14:54 UTC, Kihyun92 commented on src/List.test.jsx
> +  expect(container).toHaveTextContent('이상훈이에요');
`tasks` 목록이 잘 출력되는지 테스트해주신 것 같아요~ 

그런데 비슷한 일을 `반복`하고 있는 것 같습니다. 이 테스트들을 `tasks`를 이용해서 표현해줄 수 있을까요?

2021-02-03 14:54 UTC, Kihyun92 commented on src/Page.test.jsx
> +  ));
이 부분은 테스크의 값이 변경됨에 따라 값이 다르게 노출되는지를 확인하려는 의도일까요?

그렇다면 `rerender`를 사용하지 않고 테스트를 분리해서 표현하는 것도 좋을 것 같습니다.

예를들면 각 테스트들을 `describe-it` 구조로 분리해보는거죠.
```jest
describe('Page', () => {
  it ('test1', () => {
    ...
  }
  
  it ('test2', () => {
    ...
  }
}
```

2021-02-03 14:54 UTC, Kihyun92 commented on src/input.test.jsx
> +  const { container, getByLabelText, getByText } = render((
사이에 공백을 추가해주는 건 어떨까요? 

각각 역할이 다르기 때문에 공백을 통해 문맥상 분리를 함으로서 가독성을 높일 수 있을 것 같아요~

2021-02-04 08:56 UTC, SangHoonly commented
현재 List.test.jsx과 Input.test.jsx 코드를 describe - context - it 패턴으로 변경하여 테스트가 무엇을 하려는지 더 명확하게 알 수 있도록 하였습니다. 추후 Page.test.jsx와 App.test.jsx 또한 코드를 변경하겠습니다!

2021-02-04 13:38 UTC, Kihyun92 commented
> 현재 List.test.jsx과 Input.test.jsx 코드를 describe - context - it 패턴으로 변경하여 테스트가 무엇을 하려는지 더 명확하게 알 수 있도록 하였습니다. 추후 Page.test.jsx와 App.test.jsx 또한 코드를 변경하겠습니다!

`context`는 

`with <-> without`
`when log in <-> when log out`

처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

선택적으로 상황에 맞게 사용해주시면 됩니다 ☺️

context 사용법은 아래 문서와 아샬님의 문서를 참고해주세요.

- https://www.betterspecs.org/
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-02-04 13:48 UTC, Kihyun92 requested changes
어떻게 하면 해당 기능, 역할을 테스트로 드러낼 수 있을지 고민하시면서 사용 설명서로서 테스트 코드를 바라보시면 좋습니다.

이에 맞춰 전반적으로 테스트에 입력되는 설명 문구들을 수정해보시면 좋을 것 같아요 ㅎㅎ

2021-02-04 13:48 UTC, Kihyun92 commented on src/App.test.jsx
> +test('AppRendering', () => {
조금 더 사용 설명서와 같은 문구는 어떨까요?

예를들면 `App renders no tasks message, when initial rendering` 은 어떤가요?

2021-02-04 13:48 UTC, Kihyun92 commented on src/List.test.jsx
> +      ));
`map`메소드는 `callback` 함수의 반환값으로 이루어진 배열을 반환합니다.

지금 콜백 함수가 `side effect`를 만들어내고 있기 때문에 여기서 `map`을 사용하는건 적절한 것 같지 않습니다. 

여기서는 `forEach`메서드를 사용하는게 더 맞는 것 같아요

2021-02-04 13:48 UTC, Kihyun92 commented on src/List.test.jsx
> +      ));
매 테스트마다 반복해서 리스트 컴포넌트를 render해주고 있네요. 반복되는 로직을 함수로 분리하여 공통 처리 할 수 없을까요?

2021-02-04 13:48 UTC, Kihyun92 commented on src/input.test.jsx
> +  context('input의 value 값이 변경될 때', () => {
이 부분은 `context`로 처리하지 않아도 될 것 같아요. 인풋 값이 변경되는 것과 추가 버튼을 누른것은 별개의 테스트 같습니다.

2021-02-04 17:27 UTC, SangHoonly commented
> > 현재 List.test.jsx과 Input.test.jsx 코드를 describe - context - it 패턴으로 변경하여 테스트가 무엇을 하려는지 더 명확하게 알 수 있도록 하였습니다. 추후 Page.test.jsx와 App.test.jsx 또한 코드를 변경하겠습니다!
> 
> `context`는
> 
> `with <-> without`
> `when log in <-> when log out`
> 
> 처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.
> 
> 선택적으로 상황에 맞게 사용해주시면 됩니다 ☺️
> 
> context 사용법은 아래 문서와 아샬님의 문서를 참고해주세요.
> 
> * https://www.betterspecs.org/
> * https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

흠 고정된 템플릿이 아니라 상황에 따라 유동적으로 사용하는 거였군요... 알겠습니다!

2021-02-05 10:21 UTC, SangHoonly commented
describe, it, context를 사용해 보니, context를 사용하여 상황을 분기해서 테스트를 진행하는게 저에게 조금 더 편한 것 같아서 context를 자주 사용하게 되었습니다. 

테스트 코드 작성하는게 처음이라 그런지, 시간도 많이 걸리고 고려해야 하는 부분이 많네요. 올려주신 자료도 꼼꼼히 읽어보고, 구글링도 많이 해보고 많이 짜봐야하는데 하필 이번 주에 해커톤이랑 겹쳐버려서...

현재 App.test.jsx를 제외하고는 그래도 다 describe - it 구조로 테스트 케이스를 짰습니다. 이번주가 얼마 남지 않았지만, 그래도 남은 시간 힘내서 App.test.jsx까지 고쳐보겠습니다.

2021-02-05 14:45 UTC, Kihyun92 requested changes

2021-02-05 14:45 UTC, Kihyun92 commented on src/App.test.jsx
> +test('InputChangedView', () => {
`InputChangedView `라는 문장만 봐서는 무슨 테스트인지 명확하게 알기 어려운 것 같아요.

조금 더 무슨 테스트인지 알수 있는 문장이 좋을 것 같습니다 ㅎㅎ

2021-02-05 14:45 UTC, Kihyun92 commented on src/List.test.jsx
> +  context('When tasks is empty', () => {
`describe - context - it`이 문장처럼 이어지도록 소문자로 시작하는건 어떨까요?

2021-02-05 14:45 UTC, Kihyun92 commented on src/Page.test.jsx
> +  context('When task is not changed', () => {
지금 상황에서는 `describe`를 사용하는 것도 좋을 것 같네요~

`context`는 의도에 맞게 반대되는 상황에 주로 사용하는게 좋을 것 같습니다.

2021-02-05 14:45 UTC, Kihyun92 commented on src/Page.test.jsx
> +      expect(getByLabelText('할 일').value).toEqual('바뀌지 않아요');
원시(primitive) 자료형의 비교에는 `toBe`를 사용하는게 더 좋을 것 같아요~

- https://jestjs.io/docs/en/expect#toequalvalue

2021-02-05 14:45 UTC, Kihyun92 commented on src/input.test.jsx
> +  context('With input is empty', () => {
라인 사이에 공백 추가해주세요~

2021-02-05 14:45 UTC, Kihyun92 commented on src/input.test.jsx
> +  const renderInput = (value) => (
라인 사이에 공백 추가해주세요~

2021-02-05 14:45 UTC, Kihyun92 commented on src/input.test.jsx
> +    it('onClick works', () => {
보다 어떤 테스트인지 서술해주는건 어떨까요?

아샬님의 커맨트를 확인해보시면 좋을 것 같아요.
- https://codesoom-group.slack.com/archives/C014QSWUNHJ/p1612486289184900

2021-02-06 13:08 UTC, Kihyun92 requested changes

2021-02-06 13:08 UTC, Kihyun92 commented on src/Page.test.jsx
> +  context('when task is added', () => {
`with <-> without`
`when log in <-> when log out`
처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

지금은 할일이 등록되고, 제거되는 상황이라 반대되는 상황처럼 보이지만, 테스트의 맥락 자체가 다른것 같아요.
이 경우에는 `context`보다는 `describe`를 쓰는게 좋아보여요~

`context` 사용법은 아래 문서와 아샬님의 문서를 참고해주세요.

- https://www.betterspecs.org/
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-02-06 13:08 UTC, Kihyun92 commented on src/Page.test.jsx
> +    it('deleted tasks showed', () => {
`showed`라는 단어 없이 `deleted tasks` 라고만 해도 될 것 같은데 어떤가요?

2021-02-06 13:08 UTC, Kihyun92 commented on src/Page.test.jsx
> +      const { container } = renderPage(value, tasks.filter((task) => task.id !== 1));
할일을 제거하기 위해 filter를 사용하신 것 같아요.

실제로 저희는 어떤 방식으로 할일을 제거하고 있었나요?

2021-02-07 11:07 UTC, SangHoonly commented on src/Page.test.jsx
> +      const { container } = renderPage(value, tasks.filter((task) => task.id !== 1));
버튼을 누르면 할일이 제거되는 방식인데, 완료 버튼 작동 테스트는 item에서 이미 구현하였기에 Page에서는 "원래 있던 '할 일'이 없어졌을 시, 화면에 없어진 것이 제대로 보여지는가"를 테스트할 목적으로 테스트 케이스를 작성하였습니다.

2021-02-07 13:55 UTC, Kihyun92 approved these changes
정말 바쁜 한 주였을 것 같아요. 고생하셨습니다 💯 

과제 풀이 영상을 꼭 보시고 아샬님은 어떻게 테스트를 접근하시는지 눈여겨 보시면 좋겠습니다~

2021-02-07 13:56 UTC, merged