Write tests
CodeSoom/react-week3-assignment-1 pull request #54
Opened 2021-02-02 08:29 UTC by datalater

3주차 과제 제출합니다.

## 궁금한 점

* Page에 List 컴포넌트가 포함되어 있을 때, List를 테스트하는 코드와 Page를 테스트하는 코드가 겹쳐지는 것 같은데 뭔가 잘못된 것 같습니다. 테스트코드가 중복이 되면 잘못된 거겠죠?

## 셀프 리뷰 체크리스트

* [O] UI 반복이 없는가?
* [O]  코드의 의도가 잘 드러나는가?
* [O]  함수 이름에서 코드의 의도가 잘 드러나는가?
* [?]  관심사가 잘 분리되었는가?

## 요청 받은 코드 리뷰 목록

null

## 메타인지

### 내가 모르는 것은 무엇인가

* 화면 UI를 담당하는 두 컴포넌트가 각각 상위-하위 관계일 때 테스트 코드가 겹치게 되는 것 같은데 어떻게 하는 것이 좋은가?

### 내가 알게 된 것은 무엇인가

### 어떻게 하면 더 나을까

## 주간회고

null

2021-02-02 08:29 UTC, datalater commented
커버리지 결과를 첨부합니다.

![image](https://user-images.githubusercontent.com/8105528/106572769-32595f00-657c-11eb-9755-925caa640051.png)

2021-02-02 13:47 UTC, Kihyun92 requested changes
> Page에 List 컴포넌트가 포함되어 있을 때, List를 테스트하는 코드와 Page를 테스트하는 코드를 중복으로 작성하게 되더라고요. 테스트코드가 중복이 되면 잘못된 거겠죠?

아닙니다ㅎㅎ 상위 하위 테스트간의 테스트가 중복될 수 있습니다. 테스트에서 중요한건 `내가 얼마나 안심할 수 있는가` 같아요. 

예를 들어, Page 컴포넌트에서 Title 렌더링을 테스트한다면 그 하위에 실제 렌더링을 담당하는 Header 컴포넌트에서도 Title 렌더링을 테스트해야겠죠. 다만 Page에서는 Page 자체가 올바르게 렌더링 됐다는 걸 알 수 있는 수준에서 Title을 테스트한 것이고, Header에서는 더 많은 걸 테스트할 수도 있습니다. 물론 Page에 또 다른 컴포넌트가 있다면 그 컴포넌트가 가진 요소에 대해 테스트가 추가될 수 있습니다

각 컴포넌트마다 가지고 있는 관심사의 수준이 다르기 때문에 하위 컴포넌트의 구현상세를 과도하게 테스트하게 될 수 있습니다. 이 경우 상위에서 너무 많은 걸 알고 있다는 신호고 이는 설계적으로 문제가 될 수 있습니다.

그러나 이 부분에 대해서 지금 너무 깊게 고민하지 않으셨으면 해요. 경험치가 누적되지 않으면 사실 판단하기 어렵습니다. 그래서 훈련할 땐 극단적으로 테스트를 작성하는 걸 권합니다. 그래야 적정 수준의 테스트가 무엇인지 알 수 있게 됩니다. 지금은 떠오르는 불안들은 잠시 넣어두시고, 테스트 커버리지 100프로에 대한 집착만 남겨둬 보셔요 👍🏼

2021-02-02 13:47 UTC, Kihyun92 commented on src/App.test.jsx
> +  const utils = render(<App />);
`utils`보다는 조금 더 명확하게 `renderApp` 은 어떤가요?

그리고 구조분해 할당으로 받아와 처리해 주는것도 좋을 것 같아요~
```suggestion
  const { getByLabelText, getByText } = render(<App />);
```

2021-02-02 13:47 UTC, Kihyun92 commented on src/App.test.jsx
> +  fireEvent.change(input, { target: { value: '아무것도 하지 않기' } });
가독성 측면에서 줄바꿈 처리해주는 것도 좋을 것 같습니다~

2021-02-02 13:47 UTC, Kihyun92 commented on src/App.test.jsx
> +});
`describe-it` 구조로 표현하는 것도 좋을 것 같네요.

``` jest
describe('App', () => {
  ...
 
  it('update input value when value changes', () => {
    ...
  });

  it('~~', () => {
 ...
})
```
위와 같은 계층 구조가 될 것 같네요. 어떤가요?

2021-02-02 13:47 UTC, Kihyun92 commented on src/List.test.jsx
> +test('List shows message when tasks is empty', () => {
좋습니다. 리스트가 비었을 경우와 비어있지 않는 경우에 대해서 각각 테스트 코드를 작성해보셨네요.

추가적으로 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현해보는 건 어떤가요?

``` jest
describe('List', () => {
  context('test의 length가 0인 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('test의 length가 1 이상인 경우', () => {
    ~~ 생략 ~~
```
일단 제 임의대로 작성해봤는데(영어로 하셔도 됩니다ㅎㅎ), 차례대로 보면 `List는 test의 length가 0인 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? :)

참고
- https://ko.javascript.info/testing-mocha
-  https://www.betterspecs.org/#contexts

2021-02-03 06:21 UTC, datalater commented on src/App.test.jsx
> +});
아 너무 좋네요 말씀하신대로 바꿨습니다.

2021-02-03 06:24 UTC, datalater commented on src/List.test.jsx
> +test('List shows message when tasks is empty', () => {
궁금한 점이 있습니다.

다음과 같은 순서로 진행했더니 예상했던 바와 달라서 질문합니다.

1. context에서 렌더링합니다.
2. 첫번째 it 블록에서 테스트를 합니다. 
3. 두번째 it블록에서 테스트를 하려고 하는데 context에서 했던 렌더링이 초기화되는 것 같습니다. 맞나요?

코드는 아래에 첨부합니다.

```jsx
describe('App', () => {
  context('When there is no task', () => {
    const {
      container,
      getByLabelText,
      getByText,
      debug,
    } = render(<App />);
    const input = getByLabelText('할 일');
    const addButton = getByText('추가');

    it('should update input value when value changes', () => {
      fireEvent.change(input, { target: { value: '아무것도 하지 않기' } });
      expect(input.value).toBe('아무것도 하지 않기');
    });

    it('should add task when the button is clicked', () => {
      debug(container);
      fireEvent.change(input, { target: { value: '아무것도 하지 않기' } });
      fireEvent.click(addButton);

      debug(container); // <div /> 아무것도 없이 div만 렌더링되더라고요.
    });
  });
});
```

2021-02-03 13:52 UTC, Kihyun92 commented on src/List.test.jsx
> +test('List shows message when tasks is empty', () => {
각 테스트는 별개로 진행되어야합니다. 지금 구조는 it 내부의 각 테스트들이 같은 input, container등을 공유하고 있는 것 같아요~

``` jest
describe('App', () => {
  context('When there is no task', () => {
    function renderApp() {
      return render(<App />);
    }

    it('should update input value when value changes', () => {
      const {
        container,
        getByLabelText,
        getByText,
        debug,
      } = renderApp();
      const input = getByLabelText('할 일');
      const addButton = getByText('추가');

      fireEvent.change(input, { target: { value: '아무것도 하지 않기' } });
      expect(input.value).toBe('아무것도 하지 않기');
    });

    it('should add task when the button is clicked', () => {
      ...
    });
  });
});
```

간단하게 작성해봤습니다. 이런 식으로 처리해주는건 어떤가요?

보시고 잘못됐거나 의논이 필요한 부분이 있다면 말씀해주세요~

2021-02-03 14:05 UTC, Kihyun92 requested changes

2021-02-03 14:05 UTC, Kihyun92 commented on src/Page.test.jsx
> +test('Page shows tasks and input form', () => {
아직 작업중이신 것 같지만, Page 테스트도 tasks가 있는 경우와 없는 경우로 나뉘어 져 있네요. 

이 경우에도 describe-context-it의 구조로 나눌 수 있을 것 같군요~

2021-02-03 14:05 UTC, Kihyun92 commented on src/App.test.jsx
> +    it('should not have the task whose button is clicked', () => {
추가하고 완료하는 기능을 한번에 테스트해보신 것 같아요~

각각 테스트 하지 않고 한번에 처리한 이유가 있을까요?

2021-02-04 05:16 UTC, datalater commented on src/List.test.jsx
> +test('List shows message when tasks is empty', () => {
"각 테스트는 독립적으로 진행되어야 한다"는 걸 이제 이해했습니다.

다음과 같이 변경했습니다 c1af98b

2021-02-04 05:27 UTC, datalater commented on src/App.test.jsx
> +    it('should not have the task whose button is clicked', () => {
완료하는 기능을 테스트하려면 먼저 추가하는 작업이 필요하다고 생각해서 다음과 같이 테스트했습니다.

1. 할일을 추가한다.
2. 추가된 할일의 완료버튼을 누른다
3. 추가했던 할일 텍스트가 없어졌는지 테스트한다.

2021-02-04 05:48 UTC, datalater commented on src/Page.test.jsx
> +test('Page shows tasks and input form', () => {
넵 다음과 같이 변경했습니다

9d1f49d

2021-02-04 05:48 UTC, datalater commented on src/App.test.jsx
> +  context('When there is no task', () => {
자료 첨부해주셔서 정말 감사합니다. 다 읽었어요!

73c4514

2021-02-04 05:53 UTC, datalater commented on src/Input.test.jsx
> +  });
handleClick이 호출되는지 테스트하기 위해 어떻게 할까 고민하닥 renderInput() 함수에서 handleClick을 리턴해주게 했습니다.

이렇게 하는 게 좋은 방법일까요?

2021-02-04 13:35 UTC, Kihyun92 requested changes

2021-02-04 13:35 UTC, Kihyun92 commented on src/Input.test.jsx
> +  });
`handleClick`이 `renderInput` 내부에서 선언되어서 그렇게 처리하신 것 같아요~

그럼 함수 바깥에 선언하면 어떤가요?

이 경우엔 각 테스트별로 mock 함수를 같이 사용하기 때문에 매 테스트마다 독립적으로 해당 함수를 처리해줘야할 거에요. 어떻게 할 수 있을까요?

2021-02-04 13:35 UTC, Kihyun92 commented on src/Page.test.jsx
> +      expect(container).toHaveTextContent('아무것도 하지 않기 #2');
만약 테스크를 몇개 더 추가해서 테스트를 해야하는 경우가 생겼습니다. 지금 구조에선 하단에 계속 반복해서 추가해야 할 것 같군요.

반복되는 tasks를 테스트하려면 어떻게 할 수 있을까요?

2021-02-04 13:35 UTC, Kihyun92 commented on src/Page.test.jsx
> +    it('shows tasks', () => {
`show`와 `render` 비슷한 것 같으면서 약간 다른 느낌이네요 ㅎㅎ 

실제로 `render`를 사용해서 화면에 그려주기 때문에 `renders tasks`라는 문장은 어떤가요?

2021-02-04 13:35 UTC, Kihyun92 commented on src/List.test.jsx
> +    it('"완료" 버튼을 누르면 id 파라미터를 가진 핸들러가 실행된다.', () => {
조금 단순하게 `"완료" 버튼을 누르면 할일을 삭제한다`는 어떤가요?

2021-02-05 04:17 UTC, datalater commented on src/Input.test.jsx
> +  });
아래와 같이 해봤습니다. 어떤가요?

a878fba

2021-02-05 04:20 UTC, datalater commented on src/Page.test.jsx
> +      expect(container).toHaveTextContent('아무것도 하지 않기 #2');
```jsx
tasks.forEach(({ title }) => {
  expect(container).toHaveTextContent(title);
});
```
위와 같이 바꿔봤습니다.

1612d6f

2021-02-05 04:22 UTC, datalater commented on src/Page.test.jsx
> +    it('shows tasks', () => {
`render`가 더 적절한 단어인 것 같습니다ㅎㅎ

d7521c2

2021-02-05 04:24 UTC, datalater commented on src/List.test.jsx
> +    it('"완료" 버튼을 누르면 id 파라미터를 가진 핸들러가 실행된다.', () => {
아 그렇네요. 저는 테스트 이름에 테스트 하는 내용을 최대한 반영하려다 보니 오히려 너무 구체적인 내용이 들어간 것 같습니다.

사실 테스트하려는 건 어떻게 동작하는지가 아니라 삭제가 잘되는지 여부이므로 아래와 같이 바꿨습니다.

52c54a3

2021-02-05 04:41 UTC, datalater commented on src/List.test.jsx
> +    it('"완료" 버튼을 누르면 id 파라미터를 가진 핸들러가 실행된다.', () => {
그리고 테스트 이름이 영어와 한글이 혼용되어 있어서 통일성을 위해 모두 영어로 바꿨습니다.

6e89996

2021-02-05 08:31 UTC, datalater commented on src/App.test.jsx
> +    it('should not have the task whose button is clicked', () => {
생각해보니 여기서 추가된 할일의 완료버튼을 누르는 테스트는 context에 할일이 추가된 상태를 넣고 나서 테스트를 하는게 맞는 것 같습니다.

수정하도록 하겠습니다.

2021-02-05 08:37 UTC, datalater commented on src/App.test.jsx
> +    });
생각해보니 추가된 할일의 완료버튼을 누르는 테스트는 context에 할 일이 추가된 상태를 넣고 나서 테스트를 하는게 맞는 것 같습니다.

그런데, context에 input change 이벤트가 발생한 상황을 넣으려면 결국 it 전에 rendering을 해야 하는 문제가 발생하네요.

```jsx
context('With input being filled', () => {
  const { container, getByLabelText, getByText } = renderApp();

  const input = getByLabelText('할 일');
  const addButton = getByText('추가');

  fireEvent.change(input, { target: { value: '아무것도 하지 않기' } });
  fireEvent.click(addButton);

  it('adds a task when add button is clicked', () => {
    expect(container).toHaveTextContent('아무것도 하지 않기');
  });
});
```

이렇게 되면 테스트를 실행할 때 렌더링을 못하는데.. 어떻게 해야 하죠?

2021-02-05 13:59 UTC, Kihyun92 commented on src/Input.test.jsx
> +  });
renderInput 함수 바깥으로 빼셨군요. 공통적으로 사용해야하기 때문에 함수 바깥에 있는게 맞겠네요.

하지만, mock 함수를 공통으로 사용하다보니 다른 테스트에 영향을 받을 것 같습니다. 각 테스트는 독립적으로 실행되어야해요.

`beforeEach`를 이용해서 mocking 함수들을 초기화 시켜주면 각 테스트가 의도치 않게 동작하는 것을 막을 수 있습니다.

```jest
beforeEach(() => {
  jest.clearAllMocks();
});
```

- [https://jestjs.io/docs/en/jest-object#jestclearallmocks](https://jestjs.io/docs/en/jest-object#jestclearallmocks)
- [https://jestjs.io/docs/en/setup-teardown](https://jestjs.io/docs/en/setup-teardown)

2021-02-05 14:04 UTC, Kihyun92 commented on src/App.test.jsx
> +    });
테스트의 의도대로라면, it 함수 내에서 할일을 추가하는 과정이 필요하겠네요. 처리하신 방법이 맞습니다.

다만 테스트가 조금 커지는 느낌이 드네요 ㅎㅎ 
느끼셔서 알겠지만 App 컴포넌트가 최상단에 있다보니 이러한 비즈니스 로직 테스트가 들어갈 수 밖에 없죠. 

이런 경우에 E2E 테스트로 처리할 수도 있을 것 같습니다. 지금은 그 필요성을 느껴본거에 의미를 두면 좋겠네요 👍🏼

2021-02-05 14:10 UTC, Kihyun92 requested changes

2021-02-05 14:10 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('With tasks', () => {
`describe - context - it` 이 하나의 문장으로 이어지도록 소문자로 시작하는건 어떨까요?

2021-02-07 02:30 UTC, datalater commented on src/App.test.jsx
> +  context('With tasks', () => {
넵 반영하겠습니다

2021-02-07 02:31 UTC, datalater commented on src/App.test.jsx
> +    });
그렇군요 ㅎㅎ 감사합니다!!

2021-02-07 02:33 UTC, datalater commented on src/App.test.jsx
> +  context('With tasks', () => {
9cbe9f4

2021-02-07 12:46 UTC, datalater commented on src/Input.test.jsx
> +  });
반영했습니다.

72f1648

2021-02-07 13:17 UTC, Kihyun92 approved these changes
고생하셨습니다 ㅎㅎ 이번주도 많은 고민을 해보신 것 같아요 💯 

과제 풀이 영상을 보면서 아샬님은 어떻게 테스트를 접근하는지 보시면 좋을 것 같습니다~

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

슬랙 채널에 회고 남겨주시면 머지 하겠습니다~

2021-02-07 13:59 UTC, datalater commented
[3주차 주간 회고](https://www.notion.so/jayday/3-16e437b53fee48b689ff9da414291ab0)를 남깁니다!

2021-02-16 13:16 UTC, merged