Create test to To do App
CodeSoom/react-week3-assignment-1 pull request #55
Opened 2021-02-02 11:53 UTC by canary4651

1. Input에 test code 작성하기

2021-02-02 13:52 UTC, Kihyun92 reviewed
오 잘하시네요 👍🏼  지금까지 배웠던것들을 잘 적용해보신 것 같아요.

다른 테스트들도 기다리겠습니다 ㅎㅎ

2021-02-02 15:35 UTC, canary4651 commented on src/List.test.jsx
> +        onClick={handleClickDelete}
test가 통과가 안 되었는 데 저는 `getAllByText`를 이상하게 사용한 줄 알고 계속 헤매고 있었어요. 
에러 내용은 'onClickDelete is not a function' 이었고.... 
다시 살펴보니 제가 onClick으로 받고 있었더라구요. ㅎㅎ... 수정하고 나니까 통과됩니다!

2021-02-03 14:11 UTC, Kihyun92 requested changes
잘하고 계신 것 같아요! 나머지 테스트들도 기다리겠습니다 ㅎㅎ

2021-02-03 14:11 UTC, Kihyun92 commented on src/List.test.jsx
> +    it('rendrs message', () => {
오타가 있네요 ㅎㅎ
```suggestion
    it('renders message', () => {
```

그리고 조금 더 명확하게 무슨 메시지인지 적어주면 좋을 것 같아요~

2021-02-03 14:11 UTC, Kihyun92 commented on src/List.test.jsx
> +    it('render tasks and listen click event', () => {
하나의 테스트는 하나의 역할만 하는게 좋을 것 같아요~ 분리할 수 있을까요?

2021-02-03 14:19 UTC, canary4651 commented on src/List.test.jsx
> +    it('rendrs message', () => {
앗! ㅋㅋㅋ 저도 지금 발견해서 고치고 있었어요. 
좀 더 명확한 메시지와 함께 적겠습니다!

2021-02-03 14:20 UTC, canary4651 commented on src/List.test.jsx
> +    it('render tasks and listen click event', () => {
아하 저는 tasks들을 보여주고 완료까지 한 동작으로 생각했는데, 분리해서 보여주는 게 더 좋을 거 같아요!
분리하겠습니다 ㅎㅎ

2021-02-03 14:28 UTC, Kihyun92 requested changes

2021-02-03 14:28 UTC, Kihyun92 commented on src/List.test.jsx
> +      expect(container).toHaveTextContent('아무것도 안하기3');
`tasks` 목록이 잘 출력되는지 테스트하고 계신 것 같아요. 그런데 비슷한 일을 `반복`하는 것 같아요.

이 테스트들을 `tasks`를 이용해서 표현해줄 수 있을까요?

2021-02-03 14:33 UTC, canary4651 commented on src/List.test.jsx
> +      expect(container).toHaveTextContent('아무것도 안하기3');
안 그래도 너무 반복적인 내용들이라 이것보다 더 좋은 게 있지 않을까? 고민하고 있었어요 
반복적인 부분을 줄여서 테스트 해보겠습니다.

2021-02-03 15:06 UTC, canary4651 commented on src/Page.test.jsx
> +    expect(onChangeTitle).toBeCalled();
이 테스트 부분이 애매한 거 같아서 고민이에요. 
저는 이미 input에서 change event에 대한 test를 했다고 생각해서 page에서는 잘 나오는 지 보여주기만 하면 될 거 같은데...
일단은 input과 똑같이 해놓기는 했어요. 그런데 이미 taskTItle에는 '스트레칭 하기' 라고 넣어져있는 데, 그게 event로 불려지는 걸 다시 보는 게 좋은 테스트 방법일까? 하는 생각이 듭니다.

2021-02-04 13:04 UTC, Kihyun92 commented on src/Page.test.jsx
> +    expect(onChangeTitle).toBeCalled();
테스트하려는 컴포넌트의 역할과 관심사가 무엇인지 고민해보시고, 적절한 테스트인지 판단이 된다면 테스트를 작성해야죠.

테스트라는게 본인이 얼마나 안심할 수 있는지가 제일 중요한 것 같아요. 이 과정에서는 작업하신것처럼 중복이 발생할 수도 있구요.

하지만 지금은 이런 부분에 대해 깊게 고민하지 마시고 일단 해보시는 것도 추천합니다 ㅎㅎ 경험치가 쌓이기 전에는 적절하게 판단하기 어렵습니다. 그래서 훈련할 땐 극단적으로 테스트를 작성해보는 걸 권합니다. 😁

2021-02-04 13:14 UTC, Kihyun92 requested changes

2021-02-04 13:14 UTC, Kihyun92 commented on src/List.test.jsx
> +    it('listen click event', () => {
조금 더 사용 설명서처럼 문구가 되면 좋을 것 같아요.

`누르면 삭제되는 완료 버튼이 렌더된다`와 같은 의미는 어떤가요? 🤔

2021-02-04 13:59 UTC, canary4651 commented on src/Page.test.jsx
> +    expect(onChangeTitle).toBeCalled();
아하 네네! 
아 제가 하고 싶은 말의 의도는 저 부분이 input에서는 value가 없던 던 값을 나타나게 하는 거니까 fireEvent로 처리하는 테스트가 맞는 데
page에서는 이미 value 값이 있으니까 나타나기면 하면 된다고 테스트를 해주고 싶었어요.
그런데 테스트를 표현하는 더 괜찮은 방법이 없을까? 하고 고민했던 거였습니다! 
그러다가 `getByDisplayValue`나 `toHaveDisplayValue`를 통해 테스트 해주면 좋을 거 같아서 그걸로 수정하려구요!

2021-02-04 14:14 UTC, canary4651 commented on src/List.test.jsx
> +    it('listen click event', () => {
그냥 봤을 때 너무 간단(?)하긴 하네요 ㅎㅎ 
`renders "완료" button that is deleted when pressed` 로 수정할게요.

2021-02-04 14:17 UTC, canary4651 commented on src/Page.test.jsx
> +    expect(queryByLabelText('할 일')).toHaveDisplayValue('스트레칭 하기');
![image](https://user-images.githubusercontent.com/53050077/106904879-0cc88300-673f-11eb-9544-d19c93c55222.png)

See also:
- https://github.com/testing-library/jest-dom#readme

2021-02-04 15:42 UTC, canary4651 commented
App과 Page test code를 작성하면서 어떻게 테스트 구조를 설계해야하나 고민을 많이 하게 되었습니다. 
이미 하위 컴포넌트들인  List, Input, Item에서 상태와 기능을 테스트 하지 않았나? 하는 생각이 들었어요.  
그래서 리뷰를 참고해서 나름대로 각 페이지마다 안심할 수 있는 테스트 범위를 생각해보며 작성했습니다.

Page 같은 경우에는 Input과 List를 그려주기 때문에 값이 미리 넣어져있고 (상태 변화는 각각 Input과 List에서 테스트 해주고) 
그 값들을 잘 보여지는 거에 중점을 둬서 테스트 코드를 작성했습니다. 
그래서 title, TaskTitle, Task가 잘 보여지고 완료 버튼까지 동작하는 지를 테스트를 하려고 의도했어요. 

App은 최종적으로 상태를 관리하고 보여지게 만든다는 것을 중점을 두고 테스트를 생각했습니다. 
그래서 'Inpu에 값을 전달하고, 추가 버튼을 누르면 LIst에 추가되고 완료 버튼을 클릭하면 사라져야 한다' 이렇게 3단계로 만들었어요. 
제가 테스트를 작성한 의도는 이런데, 혹시 더 고민해봐야 하는 지점이나 바꾸면 좋겠는 부분이 있으면 마구마구 알려주세요! 

슬랙에서도 올라왔고,,, 다른 분들의 PR을 참고해도 테스트가 반복되는 가에 대한 이야기가 많았던 거 같아요. 
저도 고민했던 부분이고요! 이번 테스트를 하면서 다시 한번 관심사의 분리나 반복되는 부분에 대한 테스트 범위를 그래도 깊게(?) 생각해봤어요. 
어렵지만 재밌네요..!

2021-02-05 13:39 UTC, Kihyun92 reviewed
고생하셨습니다 ㅎㅎ

각 컴포넌트들의 관심사와 의도, 범위에 맞게 잘 테스트를 작성해 주셨어요.

고민을 많이해주셔서 확실히 리뷰드린 것 보다 더 잘해주신 것 같아요. ☺️

과제 풀이 영상을 보면서 테스트를 어떻게 작성하는지 복습해보시면 좋을 것 같습니다.

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

슬랙 채널에 회고 남겨주시면 머지 하겠습니다~

2021-02-05 13:40 UTC, Kihyun92 approved these changes

2021-02-06 06:24 UTC, canary4651 commented
> 고생하셨습니다 ㅎㅎ
> 
> 각 컴포넌트들의 관심사와 의도, 범위에 맞게 잘 테스트를 작성해 주셨어요.
> 
> 고민을 많이해주셔서 확실히 리뷰드린 것 보다 더 잘해주신 것 같아요. ☺️
> 
> 과제 풀이 영상을 보면서 테스트를 어떻게 작성하는지 복습해보시면 좋을 것 같습니다.
> 
> 이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?
> 
> 슬랙 채널에 회고 남겨주시면 머지 하겠습니다~

앗 확인이 늦었네요!!! 
회고는 `이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?` 
요 부분을 중점으로 정리해서 주말 중에 올리겠습니다!!! 
감사합니다 ㅎㅎ

2021-02-07 13:24 UTC, merged