Add Test Code for Input Component
CodeSoom/react-week3-assignment-1 pull request #59
Opened 2021-02-03 12:09 UTC by 2Zero1

2021-02-03 14:13 UTC, Kihyun92 commented
풀 리퀘스트에 내용도 적어주시면 좋을 것 같아요~

다른 동료들에게 어떤 풀리퀘스트인지 간단한 작업 내용을 설명하거나, 작업하며 하신 고민들을 적어주는거죠.

2021-02-03 14:19 UTC, Kihyun92 requested changes
input에 대한 테스트를 잘 진행해 보신것 같아요! 

나머지 테스트들도 기다리겠습니다~

2021-02-03 14:19 UTC, Kihyun92 commented on src/Input.test.jsx
> +  expect(onClick).toBeCalled();
여러 테스트를 처리하고 있는 것 같아요~

공백을 통해 각 테스트들이 어떤 테스트인지 문맥적으로 분리해주는 건 어떨까요?

예를 들면 onChange에 대한 테스트와 onClick에 대한 테스트들을 분리할 수 있겠네요 ㅎㅎ

2021-02-03 14:19 UTC, Kihyun92 commented on src/Input.test.jsx
> +  const { getByPlaceholderText, getByText } = render((
사이에 공백을 추가해주세요~

의미 있는 공백을 통해 각 역할별로 분리하여 가독성있는 코드를 만들 수도 있습니다.

2021-02-04 14:05 UTC, 2Zero1 commented
> 다른 동료들에게 어떤 풀리퀘스트인지 간단한 작업 내용을 설명하거나, 작업하며 하신 고민들을 적어주는거죠.

컨디션이 좋지 않아서 좀 회복한 후에 내일이나 주말 중으로 자세히 올리겠습니다 ^^.

2021-02-05 14:20 UTC, Kihyun92 requested changes
힘든 한 주셨을 것 같아요.

괜찮습니다. 우리에겐 아직 주말이 있으니까요.😂 

컨디션 조절 잘 하시고 화이팅입니다~

2021-02-05 14:20 UTC, Kihyun92 commented on src/List.test.jsx
> +test('빈 List', () => {
리스트가 비어있는 경우와 todo가 있는 경우에 대해서 각각 테스트 코드를 작성해보신 것 같네요 ㅎㅎ 

추가적으로 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주기 위해 `describe - context - it`의 구조로 표현해 보면 어떨까요?

``` jest
describe('List', () => {
  context('할 일이 없는 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('할 일이 있는 경우', () => {
    ~~ 생략 ~~
```
일단 제 임의대로 작성해봤는데(영어로 하셔도 됩니다ㅎㅎ), 차례대로 보면 `List는 할 일이 없는 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? ☺️

참고
- https://ko.javascript.info/testing-mocha
- https://www.betterspecs.org/#contexts

2021-02-05 14:20 UTC, Kihyun92 commented on src/Page.test.jsx
> +) => render(
불필요한 파라미터는 없을까요?

파라미터가 많다면 객체로 받는 건 어떨까요?

2021-02-05 14:20 UTC, Kihyun92 commented on src/Page.test.jsx
> +test('빈 todolist', () => {
`describe-it` 구조로 표현하는 것도 좋을 것 같네요.

``` jest
describe('Page', () => {
  ...
 
  it('할일이 없을때 ~~한다', () => {
    ...
  });

  it('~~', () => {
 ...
})
```
위와 같은 계층 구조가 될 것 같네요. 어떤가요?

2021-02-07 11:45 UTC, 2Zero1 commented on src/Page.test.jsx
> +test('빈 todolist', () => {
말씀해 주신대로 작성해보았습니다 ^^ . describe-it과 describe-context-it 두가지 방법이 있는것 같은데 언제 각각이  사용되나요 ? 
저도 찾아보겠습니다 !

2021-02-07 12:26 UTC, 2Zero1 commented
커버리지 입니다.
<img width="740" alt="스크린샷 2021-02-07 오후 9 25 49" src="https://user-images.githubusercontent.com/16797385/107146378-2f4edc00-698b-11eb-9cb4-992b5676d8ff.png">

2021-02-07 14:13 UTC, Kihyun92 commented on src/Page.test.jsx
> +test('빈 todolist', () => {
`context`를 언제 사용하는건지에 대해서 제가 명확히 설명드리지 않았군요 ㅎㅎ;

`with <-> without`
`when log in <-> when log out`

처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

context 사용법은 아래 문서와 아샬님의 문서를 참고해주세요~

- https://www.betterspecs.org/
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-02-07 15:18 UTC, Kihyun92 approved these changes
고생하셨습니다~ 

과제 풀이 영상은 보신 것 같지만, 아샬님은 어떻게 테스트를 접근하시는지 집중적으로 봐보시면 좋을 것 같아요~ ☺️

슬랙 채널에 회고 남겨주시면 머지하겠습니다~

2021-02-16 13:16 UTC, merged