test 커버리지 채우기
CodeSoom/react-week3-assignment-1 pull request #62
Opened 2021-02-03 16:36 UTC by jjkim01

첫 PR이 좀 늦었습니다 ~~

1. App 테스트는 거의 작성하지 못했습니다. App.jsx는 state 1개, 함수 3개, Page 컴포넌트 호출 1개 를 가지고 있는데요.
    5개 모두 테스트 대상인지 궁금합니다.

2. 1번과 비슷한 질문입니다. App.jsx에 있는 'handleChangeTitle()' 의 경우 App -> Page -> Input 으로 전달되는데 어디서 테스트해야되나요?

3. Input.test 에서, 30line, 35line 의 주석에 질문을 달아놓았습니다. 좋은 방법이 있을까요 ..??

4. Page.test 는 표시되는 문자열만 검사했습니다. 아마 1번과 2번 질문 답주시는거에 따라 수정 방향을 잡을 수 있을 것 같아요!

2021-02-04 14:28 UTC, Kihyun92 requested changes
테스트에서 생각할 부분은 `내가 얼마나 안심할 수 있는가` 라고 생각해요. 이 과정에선 어느 정도 중복이 발생할 수 있습니다.

예를 들어, Page 컴포넌트에서 Title 렌더링을 테스트한다면 그 하위에 실제 렌더링을 담당하는 Header 컴포넌트에서도 Title 렌더링을 테스트해야겠죠. 다만 Page에서는 Page 자체가 올바르게 렌더링 됐다는 걸 알 수 있는 수준에서 Title을 테스트한 것이고, Header에서는 더 많은 걸 테스트할 수도 있습니다. 물론 Page에 또 다른 컴포넌트가 있다면 그 컴포넌트가 가진 요소에 대해 테스트가 추가될 수 있습니다.

각 컴포넌트마다 가지고 있는 관심사의 수준이 다르기 때문에 하위 컴포넌트의 구현상세를 과도하게 테스트하게 될 수 있습니다. 이 경우 상위에서 너무 많은 걸 알고 있다는 신호고 이는 설계적으로 문제가 될 수 있습니다.

그러나 이 부분에 대해서 지금 너무 깊게 고민하지 않으셨으면 해요. 경험치가 누적되지 않으면 사실 판단하기 어렵습니다. 그래서 훈련할 땐 극단적으로 테스트를 작성하는 걸 권합니다. 그래야 적정 수준의 테스트가 무엇인지 알 수 있게 됩니다. 지금은 떠오르는 불안들은 잠시 넣어두시고, 테스트 커버리지 100프로에 대한 집착만 남겨둬 보셔요🙂

App 같은 경우는 이걸 App이 다 해야되나?? 라는 생각이 드실텐데 그래서 E2E 테스트가 있는 겁니다만 지금 정도 수준의 앱에선 고민 하지 않으셔도 됩니다ㅎㅎ

2021-02-04 14:28 UTC, Kihyun92 commented on src/List.test.jsx
> +test('List has more than one item', () => {
좋습니다. 리스트가 비었을 경우와 비어있지 않는 경우에 대해서 각각 테스트 코드를 작성해보셨네요.

다만 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현해볼 수 있을 것 같아요.

``` jest
describe('List', () => {
  context('할일이 없는 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('할 일이 있는 경우', () => {
    ~~ 생략 ~~
```
일단 제 임의대로 작성해봤는데, 차례대로 보면 `List는 할 일이 없는 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? ㅎㅎ

참고
- https://ko.javascript.info/testing-mocha
-  https://www.betterspecs.org/#contexts

2021-02-04 14:28 UTC, Kihyun92 commented on src/List.test.jsx
> +  ));
매 테스트마다 반복해서 리스트 컴포넌트를 render해주고 있네요. 반복되는 로직을 함수로 분리하여 공통 처리 할 수 없을까요?

2021-02-04 14:28 UTC, Kihyun92 commented on src/Input.test.jsx
> +  // 23~29: onChangeTitle()가 해야할 일을 수동으로 구현한 것 같은데.. 더 좋은 방향이 있을까요?
무엇을 확인하고 싶은지 좀 더 고민해보시면서 작성해보세요.

`Input 컴포넌트에서 값이 변경되면 onChange 이벤트가 호출된다` 를 테스트해야할 것 같네요.

2021-02-04 14:28 UTC, Kihyun92 commented on src/Input.test.jsx
> +  // expect(todoTitleField.value).toBe('');
추가 버튼이 눌렸을때 `handleClick` 함수가 호출됐는지 확인하는게 우선일 것 같아요.

주석 달아주신 부분은 `getByLabelText`을 이용할 수 있을 것 같아요.

- https://testing-library.com/docs/queries/about/#priority

2021-02-05 15:25 UTC, jjkim01 commented
올려주신 참고 코드들이 생각하는데 큰 도움이 되었습니다 !!
여전히 App 컴포넌트에서 함수들을 테스트하는게 어색합니다만..

getByLabelText ... 등등 getBy 들 종류가 많은데 어느 시점에 뭐가 적절하다 이런 기준도 있을까요 ??

2021-02-06 12:48 UTC, Kihyun92 requested changes

2021-02-06 12:48 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('화면이 띄워질 때', () => {
`with <-> without`
`when log in <-> when log out`
처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

지금은 위와 같은 상황이 아니기 때문에 `context`보다는 `describe`를 쓰는게 좋아보여요~  다른 테스트들도 수정해주세요

`context` 사용법은 아래 문서와 아샬님의 문서를 참고해주세요.

- https://www.betterspecs.org/
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-02-06 12:48 UTC, Kihyun92 commented on src/List.test.jsx
> +    return container;
함수 내에서 바로 리턴해도 좋을 것 같아요~
```suggestion
    return render((
      <List tasks={tasks} />
    ));
```

2021-02-06 12:48 UTC, Kihyun92 commented on src/List.test.jsx
> +    });
여러개의 할일이 있는 경우는 어떻게 테스트 할 수 있을까요?

2021-02-06 12:51 UTC, Kihyun92 commented
> 올려주신 참고 코드들이 생각하는데 큰 도움이 되었습니다 !!
> 여전히 App 컴포넌트에서 함수들을 테스트하는게 어색합니다만..
> 
> getByLabelText ... 등등 getBy 들 종류가 많은데 어느 시점에 뭐가 적절하다 이런 기준도 있을까요 ??

이 부분은 너무 많은 쿼리들이 있어서 분류해드리기는 조금 어렵네요 😅
[문서](https://testing-library.com/docs/queries/about/#priority)를 보셔서 아시겠지만, 각 query들마다 의도된 부분들이 있습니다 ㅎㅎ
문서를 잘 읽어보고 이것 저것 사용하시다보면 자연스레 습득될 부분이라고 생각합니다 👍🏼

2021-02-06 14:36 UTC, jjkim01 commented on src/App.test.jsx
> +  context('화면이 띄워질 때', () => {
context 없이 describe만 쓸 때 이름을 잘 짓는 방법도 있을까요?

아샬님 문서도 context가 있는 예제고, given이라는 약간 다른 개념도 나와서
오히려 describe만 쓰는 상황에서 참고하려니 더 헷갈리네요.

App은
describe('할일 추가, 완료 테스트', () => {

Page
describe('화면에 표시된 내용 테스트', () => {

Input
describe('입력값 변화, 할일 추가 함수 테스트', () => {

이런식으로 해봤는데요..
의도하신 정답에 가까운지 잘 모르겠어요.

다양한 테스트코드 예제를 더 접해보지 않아서인지,
아직도 컴포넌트로 나뉜 관심사들을 정확히 이해하지 못해서인지,
하면 할수록 스트레스인 작업이네요,, ㅜㅜ

2021-02-06 14:47 UTC, jjkim01 commented on src/List.test.jsx
> +    });
말씀하신 테스트 케이스도 추가해봤습니다!
생각해보니 1개일 때랑 2개 이상일 때는 다른 테스트로 해주는 게 좋을 것 같네요

2021-02-06 14:51 UTC, jjkim01 commented
> > 올려주신 참고 코드들이 생각하는데 큰 도움이 되었습니다 !!
> > 여전히 App 컴포넌트에서 함수들을 테스트하는게 어색합니다만..
> > getByLabelText ... 등등 getBy 들 종류가 많은데 어느 시점에 뭐가 적절하다 이런 기준도 있을까요 ??
> 
> 이 부분은 너무 많은 쿼리들이 있어서 분류해드리기는 조금 어렵네요 😅
> [문서](https://testing-library.com/docs/queries/about/#priority)를 보셔서 아시겠지만, 각 query들마다 의도된 부분들이 있습니다 ㅎㅎ
> 문서를 잘 읽어보고 이것 저것 사용하시다보면 자연스레 습득될 부분이라고 생각합니다 👍🏼

옙 참고문서 다시 링크주셔서 감사합니다~~
doc에서 알 수 있는 정보와 멘토님들이 주실 수 있는 정보가 다를 수 있을거라 생각해서요!

배우는 초기라 아무래도 실용적인 팁이 더 있을까 생각해봤습니다 ㅎㅎ
일단 문서 숙지하고 검색도 해보고 연습하면서 습득하겠습니다 ~~

2021-02-07 13:44 UTC, Kihyun92 approved these changes
고생하셨습니다 ㅎㅎ

과제 풀이 영상을 꼭 보시고 아샬님은 어떻게 테스트를 접근하시는지 눈여겨 보시면 좋겠습니다~

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

슬랙 채널에 회고 남겨주시면 머지 하겠습니다~ 😁

2021-02-07 15:03 UTC, jjkim01 commented
> > > 올려주신 참고 코드들이 생각하는데 큰 도움이 되었습니다 !!
> > > 여전히 App 컴포넌트에서 함수들을 테스트하는게 어색합니다만..
> > > getByLabelText ... 등등 getBy 들 종류가 많은데 어느 시점에 뭐가 적절하다 이런 기준도 있을까요 ??
> > 
> > 
> > 이 부분은 너무 많은 쿼리들이 있어서 분류해드리기는 조금 어렵네요 😅
> > [문서](https://testing-library.com/docs/queries/about/#priority)를 보셔서 아시겠지만, 각 query들마다 의도된 부분들이 있습니다 ㅎㅎ
> > 문서를 잘 읽어보고 이것 저것 사용하시다보면 자연스레 습득될 부분이라고 생각합니다 👍🏼
> 
> 옙 참고문서 다시 링크주셔서 감사합니다~~
> doc에서 알 수 있는 정보와 멘토님들이 주실 수 있는 정보가 다를 수 있을거라 생각해서요!
> 
> 배우는 초기라 아무래도 실용적인 팁이 더 있을까 생각해봤습니다 ㅎㅎ
> 일단 문서 숙지하고 검색도 해보고 연습하면서 습득하겠습니다 ~~



> 고생하셨습니다 ㅎㅎ
> 
> 과제 풀이 영상을 꼭 보시고 아샬님은 어떻게 테스트를 접근하시는지 눈여겨 보시면 좋겠습니다~
> 
> 이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?
> 
> 슬랙 채널에 회고 남겨주시면 머지 하겠습니다~ 😁

감사합니다 !
회고에 느낌을 작성했습니다.
잘 모르겠지만 빨리 나아가고 싶은 마음에 스트레스가 많지만
한주 한주 지나면서 배우는게 하나 이상씩 있는 것 같아서 좋습니다!!

2021-02-16 13:15 UTC, merged