Feature/test jest
CodeSoom/react-week3-assignment-1 pull request #63
Opened 2021-02-03 17:25 UTC by heejinlee07

`List.jsx`에 대한 test 작성
- task가 있을 때와 없을 때의 경우를 test

2021-02-04 14:35 UTC, Kihyun92 requested changes
`prettier`를 추가하신 이유가 있나요?

동료들과 협의하에 코드 컨벤션을 맞춘 상황에서 `prettier`를 사용하는 것은 찬성합니다만, 그렇지 않은 경우엔 본인만 이해할 수 있는 혹은 의도치 않은 처리가 이루어지게 됩니다.

직접 공백 하나하나, 줄바꿈 하나하나에도 본인의 의도를 집어 넣어보는 건 어떨까요?

이러한 이유에서 코드숨 과정에서는 `prettier`를 권하지 않고 있어요.

2021-02-04 14:35 UTC, Kihyun92 commented on src/List.jsx
> +    return <p>할 일이 없어요!</p>;
`prettier` 로 인해 변경된 부분일까요?

2021-02-04 14:35 UTC, Kihyun92 commented on src/List.test.jsx
> +test('Task가 없을 경우', () => {
할일이 있는 경우와 없는 경우에 대해서 각각 테스트 코드를 작성해보신 것 같아요~ 좋습니다 👍🏼 

추가적으로 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현해 볼 수 있습니다.

``` jest
describe('List', () => {
  context('할 일이 없는 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('할 일이 있는 경우', () => {
    ~~ 생략 ~~
```
일단 제 임의대로 작성해봤는데(영어로 하셔도 됩니다ㅎㅎ), 차례대로 보면 `List는 할 일이 없는 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? ☺️

참고
- https://ko.javascript.info/testing-mocha
-  https://www.betterspecs.org/#contexts

2021-02-04 14:35 UTC, Kihyun92 commented on src/List.test.jsx
> +  expect(container).not.toHaveTextContent('css');
줄 바꿈이 필요할 것 같습니다. 이 부분도 prettier의 영향일까요? ㅠㅠ

2021-02-06 12:15 UTC, Kihyun92 commented
@heejinlee07 님~ 잘 진행 중이신가요? 

추가 커밋이 없는 것 같아요 🙂 혹시 어려운점이 있다면 말씀해주세요~

2021-02-07 16:32 UTC, heejinlee07 commented
@Kihyun92 Test 코드를 처음 짜보다보니 막혀서 좀 늦었네요 다음에는 시간준수하도록 하겠습니다😂

2021-05-16 09:13 UTC, merged