[미완성] Test todo list
CodeSoom/react-week3-assignment-1 pull request #66
Opened 2021-02-04 15:22 UTC by ErickRyu

2021-02-05 14:47 UTC, Kihyun92 commented
성진님~ 풀리퀘스트에는 가능하면 어떤 작업이 있었는지, 간단하게 요약을 해주시거나 혹은 작업을 하면서 했던 고민, 생각 등을 적어주시면 동료들이 보고 리뷰하기 좋을 것 같습니다

2021-02-05 15:05 UTC, Kihyun92 requested changes
고민을 많이 해보고 계신 것 같아요 👍🏼 

의논이 필요하다면 편하게 말씀주세요~

2021-02-05 15:05 UTC, Kihyun92 commented on src/Input.test.jsx
> +  // Todo: test value
어떻게 하면 깔끔하게 Input 컴포넌트의 역할을 드러낼 수 있을까요? 사용 설명서 측면에서 테스트 코드를 바라보는 것도 좋습니다.

해당 컴포넌트를 사용하는 사람에게 예제로 테스트를 제공하는거죠. 무엇을 보여주고 싶으신가요?

“Input 컴포넌트에서 값이 변경되면 onChange 이벤트가 호출된다.“ 일 것 같아요.

그럼 어떤걸 expect 해야할까요?

2021-02-06 12:36 UTC, Kihyun92 requested changes

2021-02-06 12:36 UTC, Kihyun92 commented on src/App.test.jsx
> +  it('할 일을 등록하면 리스트에 뜬다.', () => {
리스트에 노출된다, 출력된다 혹은 그려진다 라는 말은 어떨까요? ㅎㅎ

2021-02-06 12:36 UTC, Kihyun92 commented on src/App.test.jsx
> +    expect(container).toHaveTextContent('할 일 2번');
등록시 리스트에 노출되는건 위에 테스트에서 확인 한 것 같아요.

그렇담 각각 확인하는 것 보다 개수를 체크하면 어떨까요?

두개를 등록하면 두개가 있다와 같은 식으로요.

2021-02-06 12:36 UTC, Kihyun92 commented on src/App.test.jsx
> +    expect(container).toHaveTextContent('할 일 2번');
확인 > 삭제를 여러번 확인해봐야할까요? 🤔

2021-02-07 08:22 UTC, ErickRyu commented on src/App.test.jsx
> +  it('할 일을 등록하면 리스트에 뜬다.', () => {
뜬다 라는 말이 조금 불명확하고 "모달창이 뜬다" 처럼 쓰이는 것이 적절해서 제안을 주신것일까요? 
어떤것들을 떠올리셨는지도 궁금합니다ㅎㅎ

2021-02-07 08:30 UTC, ErickRyu commented on src/App.test.jsx
> +    expect(container).toHaveTextContent('할 일 2번');
key값을 잘못 설정했을 경우 추가,삭제 반복 과정에서 잘못된 아이템이 삭제될 수도 있다고 생각했어요.

2021-02-07 08:32 UTC, ErickRyu commented on src/App.test.jsx
> +    expect(container).toHaveTextContent('할 일 2번');
탐색적 테스트를 할 경우, 순서를 복잡하게 바꾸는 방식은 중요하다고 알고 있어요. 
두 개 아이템으로만 추가,삭제를 테스트하는 것으로 만족을 시켜놓고, 나중에 문제가 발생하면 테스트를 추가하면 좋지 않을까 생각했어요. 
혹시 이 부분은 어떻게 생각을 해볼 수 있을까요?

2021-02-07 08:32 UTC, ErickRyu commented on src/App.test.jsx
> +    expect(container).toHaveTextContent('할 일 2번');
사이즈를 확인하는 방식으로 바꿔봤어요

2021-02-07 08:33 UTC, ErickRyu commented on src/Input.test.jsx
> +  // Todo: test value
`사용 설명서 측면에서` 생각하는 것이 중요하네요 ㅎㅎ
피드백과 풀이 영상을 참고해서 onChange handler가 호출된다를 expect 하도록 변경했어요.

2021-02-07 08:36 UTC, ErickRyu commented on src/List.test.jsx
> +  rerender((
List에 적용을 해보았습니다. context-describe-it이 좋아보여요.
제가 회사에서 laravel, php를 사용해서 이 패턴을 적용하면 좋겠다 싶어서, 검색을 해보니 describe-it 패턴을 만들기 위한 git repository는 하나 찾았는데, 이 context-describe-it이 구현된 건 찾지 못했어요. 
혹시 이렇게 원하는 것을 찾지 못하는 경우에 기현님은 어떤 옵션들을 생각하실까요?

2021-02-07 15:08 UTC, Kihyun92 commented on src/List.test.jsx
> +  rerender((
오,, 현업에도 적용해보셨군요!! 👍🏼 

음 `context`의 역할은 테스트 코드들을 계층 구조로 나누고 보다 대비되는 테스트를 보기 쉽게 처리해주는 것 같아서, 일단은 `describe-context-it` 대신 `describe-describe-it`로 구조를 분리해서 의도를 전달할 것 같아요.

2021-02-07 15:09 UTC, Kihyun92 commented on src/App.test.jsx
> +  it('할 일을 등록하면 리스트에 뜬다.', () => {
맞아요ㅎㅎ 뜬다라고 하면 render 보다는 open 과 같은 개념이 떠올랐던 것 같아요 ☺️

2021-02-07 15:11 UTC, Kihyun92 commented on src/App.test.jsx
> +    expect(container).toHaveTextContent('할 일 2번');
그런 의도라면 여러번 삭제해볼 필요가 있겠네요!

2021-02-07 15:23 UTC, Kihyun92 approved these changes
고생하셨습니다 ㅎㅎ

쉽지 않은 과제였는데, 많이 고민해주신 것 같아요 💯 

과제 풀이 영상은 보신 것 같지만, 아샬님은 어떻게 테스트를 접근하시는지에 집중해서 보시면 좋을 것 같습니다~

2021-02-07 15:23 UTC, merged