[3주차] To-do 테스트 작성하기
CodeSoom/react-week3-assignment-1 pull request #75
Opened 2021-05-17 13:04 UTC by Hamill210

완성은 못했지만 월요일에 꼭 PR을 보내고 싶어서 PR을 보냅니다. 이번주도 잘 부탁드립니다!!

### 코드 커버리지
- Item.jsx (완)
- List.jsx (완)
- Input.jsx (미완)
- Page.jsx (미완)
- App.jsx (미완)

### 할 일
- ESLint 통과 (X)
- 모든 인수 테스트 통과 (X)
- 테스트 커버리지 100% 달성 (X)

2021-05-17 13:54 UTC, Hamill210 commented
### 코드 커버리지
- Item.jsx (완)
- List.jsx (완)
- Input.jsx (완)
- Page.jsx (완)
- App.jsx (완)

### Done
- ESLint 통과
- 모든 인수 테스트 통과
- 테스트 커버리지 100% 달성

2021-05-17 13:57 UTC, Hamill210 commented
집중해서 풀었더니 생각보다 일찍 마무리가 되었습니다.

하지만 코드 커버리지 달성에만 집중하다 보니
테스트 작성 방법(RED-GREEN-REFACTORING)을 잘 지키면서 완성시켰는지 의문입니다.
빨리 풀기보다 TDD 사고법을 고수했어야 했는데... 회초리는 달게 받겠습니다.

2021-05-17 14:06 UTC, Hamill210 commented
그리고 테스트 커버리지가 생각했던 것보다 쉽게 통과되면서
해당 컴포넌트에서 기대해야 할 테스트는 무엇인지, 어떤 테스트를 해야하는지 생각이 매우 모호해졌습니다. 

구현하기 전에는 이렇게 생각했습니다.
1. Input 컴포넌트 - 할 일 입력, 추가하는 걸 테스트하자
2. Item 컴포넌트 - 할 일 제거되는 걸 테스트하자

구현한 후 결과는 이랬습니다.
1. App 컴포넌트 - 할 일 입력, 추가, 제거를 테스트해보세요. <- App 컴포넌트에서 이걸 테스트하는 게 맞는걸까?
2. Input 컴포넌트 - '할 일추가' 텍스트만 보여줘도 통과입니다. <- Input 컴포넌트에서 동작 테스트를 안해도 통과과 되네??

제가 아직 테스트에 대해 깊이 고민해보지 않은 결과라 생각합니다. TDD 책을 읽어보면 해답이 나올까요? 흠...
피드백주시면 정말 감사하겠습니다. (_ _)

2021-05-17 15:12 UTC, Kihyun92 requested changes
빠른 PR 좋습니다! 👍🏼 

> 하지만 코드 커버리지 달성에만 집중하다 보니
테스트 작성 방법(RED-GREEN-REFACTORING)을 잘 지키면서 완성시켰는지 의문입니다.

아무래도 기존에 작성된 코드에 테스트를 추가하는 작업이다보니 TDD의 `Red-Green-Refactoring`를 지키긴 쉽지 않죠 :) 이번주는 테스트에 대해 여러 실험을 해보는 과정이라고 생각해보시면 좋을 것 같아요~

> 해당 컴포넌트에서 기대해야 할 테스트는 무엇인지, 어떤 테스트를 해야하는지 생각이 매우 모호해졌습니다.

우리가 이전 과제에서 배웠던 관심사 측면에서도 고민해보시면 좋을 것 같아요 :) 테스트에 정답은 없습니다. 아무래도 본인이 얼마나 안심할 수 있는가에 달려있을 것 같아요 ㅎㅎ
이번 과제는 너무 고민 마시고 커버리지 100%에 맞춰 극단적으로 테스트를 해보셔도 좋을 것 같습니다~

2021-05-17 15:12 UTC, Kihyun92 commented on src/List.test.jsx
> +});
할일이 있는 경우와 없는 경우에 대해서 테스트 해보셨군요 😊

최상위 테스트는 한개만 존재하도록 해주세요. `describe - it`의 구조를 사용할 수 있을 것 같네요.(describe는 중첩 가능합니다)

- https://jestjs.io/docs/api#describename-fn

지금의 경우에는 `describe - context - it`과 같이 표현해줘도 좋을 것 같네요. 

`with <-> without` `when log in <-> when log out` 처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

context 사용법은 아래 문서들을 참고해주세요.

- https://www.betterspecs.org/

- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-05-17 15:12 UTC, Kihyun92 commented on src/Input.test.jsx
> +test('add Todo', () => {
input 컴포넌트에는 추가 버튼도 있는데, 해당 버튼에 대해서도 테스트해주면 좋을 것 같네요 :)

2021-05-18 13:03 UTC, Hamill210 commented
> 우리가 이전 과제에서 배웠던 관심사 측면에서도 고민해보시면 좋을 것 같아요 :) 테스트에 정답은 없습니다. 아무래도 본인이 얼마나 안심할 수 있는가에 달려있을 것 같아요 ㅎㅎ
> 이번 과제는 너무 고민 마시고 커버리지 100%에 맞춰 극단적으로 테스트를 해보셔도 좋을 것 같습니다~

테스트에 정답이 없다는 말이 너무 와닿네요 :)
이전 자바에서 JUnit을 통해 유닛테스트했을 때도... 항상 막막하던게 테스트 작성이였는데...
항상 감사합니다!

2021-05-18 13:09 UTC, Hamill210 commented on src/App.test.jsx
> +  expect(container).toHaveTextContent('할 일이 없어요!');
중복되는 테스트는 제거하고 이벤트 발생에 따라 확인해야 할 부분만 확인하는 방법이 있겠죠?
지금은 확실히 모르겠습니다. 좀더 공부해보고 반영해보겠습니다.

2021-05-18 13:11 UTC, Hamill210 commented on src/List.test.jsx
> +});
이번 과제에선 describe - it 방식은 사용하지 않을 줄 알았는데...! 또 새로운 방법이군요 ㅎㅎ
공부해보고 바로 반영해보겠습니다. 피드백 감사합니다!

2021-05-18 13:12 UTC, Hamill210 commented on src/Input.test.jsx
> +test('add Todo', () => {
넵 해당 버튼에 대해서도 테스트해보겠습니다. 감사합니다!!

2021-05-18 15:29 UTC, Kihyun92 requested changes

2021-05-18 15:29 UTC, Kihyun92 commented on src/List.test.jsx
> +  ).container;
컴포넌트를 랜더하는 부분이 중복되는 것 같아요~ 테스트 코드도 리팩터링 대상입니다. 

중복을 없앨 방법은 없을까요?

2021-05-19 13:31 UTC, Hamill210 commented on src/App.test.jsx
> +  expect(container).toHaveTextContent('추가');
넵 알겠습니다! 쿼리를 사용해서 개선해보겠습니다. 피드백 감사합니다!

2021-05-19 13:32 UTC, Hamill210 commented on src/List.test.jsx
> +  ).container;
다른 리뷰를 보니 given2 라이브러리를 이용하면 중복 제거에 도움이 된다고 하시더군요! 개선해서 반영해보겠습니다 ㅎㅎ 피드백 감사합니다!

2021-05-19 15:07 UTC, Kihyun92 requested changes
테스트 코드를 잘 작성해주고 계신 것 같습니다 👍🏼

2021-05-19 15:07 UTC, Kihyun92 commented on src/List.test.jsx
> +  });
조금 더 명확하게 `context` 를 사용해봐도 좋을 것 같네요~

- https://github.com/CodeSoom/react-week3-assignment-1/pull/75#discussion_r633613421

2021-05-22 06:09 UTC, Hamill210 commented
@Kihyun92 기현님 안녕하세요.
한동안 코드 수정을 안해서 죄송하다는 말씀드립니다.
딱히.. 이번 과제는 더 하고싶다는 동기부여가 생기지 않았는데요...

원래 필요한 게 생기면 공부하는 스타일인데 이미 코드 커버리지는 달성했고...
context만 수정하면 된다고 말씀주셔서.. 그만 제가 게을러진것같습니다.
 
context 부분은 수정해서 반영했습니다.
아샬님이 강의해주신 부분까지 습득해서 코드 반영 후 푸쉬하겠습니다.
감사합니다!

2021-05-22 15:10 UTC, Kihyun92 approved these changes
한울님께서 과제를 잘 해주셔서 피드백을 드릴 부분이 많지 않았지만, 저도 리뷰를 더 깊게 고민하고 드렸어야했는데 라는 아쉬움이 남네요 😅

과제 풀이 영상을 잘 봐주신 것 같아요 ㅎㅎ 아샬님은 어떤 방식으로 테스트 코드에 접근하시는지 보시면 좋을 것 같습니다~

이번 과제를 통해 무엇을 배우셨나요? 더 배우고 싶으신게 있는지 정리해보셔도 좋을 것 같아요~

슬랙 채널에 회고 남겨주시면 머지하도록 하겠습니다 😊

2021-05-22 15:10 UTC, Kihyun92 commented on src/practice/List.test.jsx
> +      expect(getByText(/Task-2/)).not.toBeNull();
지금은 확인하는 task가 두개밖에 없지만, task를 추가로 확인해야하는 경우엔 계속 하단에 같은 로직을 추가해야할 것 같군요.

다시말해 tasks를 이용해 반복되는 로직을 처리할 방법이 있을까요?

2021-05-22 15:25 UTC, Hamill210 commented
과제 풀이 영상을 통해 

습득한 정보
1. toBeNull() 사용법!!
2. 사용자 테스트(e2e)는 CodeceptJS 활용
3. jest-plugin-context 를 이용하면 describe-context-it 방식으로 구현 가능
4. npx jest --watchAll --verbose
    - verbose 옵션을 주면 계층구조로 테스트 확인 가능

습득한 지식
1. App 컴포넌트와 같은 데이터를 다루는 컴포넌트를 테스트 할 땐 초기값으로 넣어준 데이터가 렌더링되고 있는지 확인하는 테스트를 해볼 것.
2. Page 컴포넌트와 같은 화면을 그리는 컴포넌트를 테스트 할 땐 부모컴포넌트로 부터 받는 데이터가 제대로 그려지는지 테스트 해볼 것.
3. TDD 구현 시 컴포넌트를 먼저 구현하지 말고, 
    1. 컴포넌트에 대한 모습을 개략적으로 만들어놓고(<Page ...props />), 
    2. 테스트 작성하면서 기능이 돌아가게 만들고, 
    3. 테스트를 참고하여 컴포넌트를 구현하는 방법을 고려해볼 것.

----
고민이 필요한 주제
1. 어떤 것을 테스트하고 싶은가
2. 왜 테스트하는가
3. 내가 안심 할 수 있는 범위까지의 테스트란? 나란 존재가 완벽하지 않기에... 나는 안심해도 예상치 못한 사이드 이펙트가 발생 할 수 있음.

궁금해서 공부하고 싶은 주제
- 상태값을 테스트하는 방법
- 구현된 함수를 테스트하는 방법

2021-05-23 14:02 UTC, Hamill210 commented on src/practice/List.test.jsx
> +      expect(getByText(/Task-2/)).not.toBeNull();
forEach문을 통해 반복되는 것들을 처리해주면 될 것 같습니다~ 같은 로직을 가지고 있는 부분들 수정해서 반영하겠습니다.

```javascript
const tasks = [
  { id:1, title: 'title #1' },
];

tasks.forEach((task) => {
  expect(getByText(task.title)).not.toBeNull();
});
```

2021-05-31 15:45 UTC, merged