코드 초기화
CodeSoom/react-week3-assignment-1 pull request #76
Opened 2021-05-17 13:14 UTC by hxunz

코드 초기화 후 과제 진행하겠습니다.

2021-05-17 15:16 UTC, hxunz commented
우선 List 테스트 코드 먼저 만들려고 해봤습니다!
Item 테스트 코드를 가져와서 List로 변경했는데 
List 테스트코드와 Item 테스트코드가 똑같아도 되는걸까요,,?

2021-05-17 15:18 UTC, Kihyun92 reviewed
리스트 컴포넌트 테스트를 작성해주셨네요 👍🏼  강의 영상을 잘 봐주신 것 같습니다 ㅎㅎ

서비스 관점에서 봤을때 리스트 컴포넌트에서는 어떤 처리를 해줘야하나요?

리스트가 있는 경우와 없는 경우에 대해서도 처리가 필요할 것 같아요. 버튼들이 눌렸을때 테스트를 해볼수도 있을 것 같구요 :)

2021-05-18 12:11 UTC, hxunz commented
버튼이 눌렸을 때 테스트는 어떤 버튼을 의미하는 건가요??

2021-05-18 13:24 UTC, kimkhyun commented
> 버튼이 눌렸을 때 테스트는 어떤 버튼을 의미하는 건가요??

리스트 내 아이템에 완료 버튼들 말씀드렸습니다 😁

2021-05-20 08:19 UTC, hxunz commented
Page 테스트에서 Input과 List에서 사용된 테스트들이 동일하게 들어가도 되는걸까요???

2021-05-20 13:43 UTC, Kihyun92 commented
> Page 테스트에서 Input과 List에서 사용된 테스트들이 동일하게 들어가도 되는걸까요???

테스트에서 생각할 부분은 '내가 얼마나 안심할 수 있는가' 라고 생각해요. 이 과정에선 어느 정도 중복이 발생할 수 있습니다.

예를 들어, Page 컴포넌트에서 Title 렌더링을 테스트한다면 그 하위에 실제 렌더링을 담당하는 Header 컴포넌트에서도 Title 렌더링을 테스트해야겠죠. 다만 Page에서는 Page 자체가 올바르게 렌더링 됐다는 걸 알 수 있는 수준에서 Title을 테스트한 것이고, Header에서는 더 많은 걸 테스트할 수도 있습니다. 물론 Page에 또 다른 컴포넌트가 있다면 그 컴포넌트가 가진 요소에 대해 테스트가 추가될 수 있습니다.

각 컴포넌트마다 가지고 있는 관심사의 수준이 다르기 때문에 하위 컴포넌트의 구현상세를 과도하게 테스트하게 될 수 있습니다. 이 경우 상위에서 너무 많은 걸 알고 있다는 신호고 이는 설계적으로 문제가 될 수 있습니다.

그러나 이 부분에 대해서 지금 너무 깊게 고민하지 않으셨으면 해요. 경험치가 누적되지 않으면 사실 판단하기 어렵습니다. 그래서 훈련할 땐 극단적으로 테스트를 작성하는 걸 권합니다. 그래야 적정 수준의 테스트가 무엇인지 알 수 있게 됩니다. 지금은 떠오르는 불안들은 잠시 넣어두시고, 테스트 커버리지 100프로에 대한 집착만 남겨둬 보셔요🙂

2021-05-20 13:50 UTC, Kihyun92 requested changes
잘 진행중이신 것 같네요 😊 

많은 고민을 하면서 진행하시는 것 같아 좋습니다 👍🏼

2021-05-20 13:50 UTC, Kihyun92 commented on src/Input.test.jsx
>    fireEvent.click(getByText('추가'));
추가 버튼이 클릭 된 이후에 원하는 함수가 올바르게 호출됐는지 확인해봐도 좋을 것 같아요 :)

2021-05-20 13:50 UTC, Kihyun92 commented on src/List.test.jsx
> +test('emptyList', () => {
할일이 있는 경우와 없는 경우에 대해서 테스트 해보셨군요 😊

최상위 테스트는 한개만 존재하도록 해주세요. `describe - it`의 구조를 사용할 수 있을 것 같네요.(describe는 중첩 가능합니다)

- https://jestjs.io/docs/api#describename-fn

지금의 경우에는 `describe - context - it`과 같이 표현해줘도 좋을 것 같네요. 

`with <-> without` `when log in <-> when log out` 처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

context 사용법은 아래 문서들을 참고해주세요.

- https://www.betterspecs.org/

- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-05-20 13:50 UTC, Kihyun92 commented on src/Page.test.jsx
> +    <Input />
Input 이 아닌, Page 컴포넌트를 테스트해줘야할 것 같아요~

2021-05-20 13:50 UTC, Kihyun92 commented on src/Page.test.jsx
> +test('List', () => {
추후 수정 예정이시겠지만, 이 부분도 List 가 아닌 Page 컴포넌트를 테스트해줘야합니다~

2021-05-21 10:16 UTC, hxunz commented
https://jestjs.io/docs/api#describename-fn
이것을 참고하여 describe을 사용해보았는데요 
describe - context - it 과 같이 표현하는건 익숙치 않아서 좀 더 공부 해보고 코드 수정해보겠습니다!

2021-05-21 14:48 UTC, Kihyun92 requested changes
진행하실때 린트는 항상 돌려보면서 진행해보시면 좋습니다 :)

도움이 필요하면 언제든 말씀해주세요~!

2021-05-21 14:48 UTC, Kihyun92 commented on src/Input.test.jsx
>    expect(handleChange).toBeCalled();
`추가` 버튼이 클릭되면 어떤 함수가 호출되나요? `handleChange`가 호출되는게 맞나요??

그리고 이벤트를 발생시킨 이후에 함수가 호출됐는지 확인해주는게 맞을 것 같아요~

2021-05-21 14:48 UTC, Kihyun92 commented on src/List.test.jsx
> +        task={task}
현재 List 컴포넌트에서는 tasks를 props 로 받는 것 같아요~

그리고 현재 테스트에서는 배열이 아닌 객체로 넘기고 있는 것 같아요. 반면 아래 테스트(empty List)에는 빈 스트링('')로 되어있네요.

넘겨주는 데이터가 어떤 형식인지 다시 체크해보면 좋을 것 같습니다 :)

2021-05-21 14:48 UTC, Kihyun92 commented on src/List.test.jsx
> +    ));
랜더해주는 코드가 중복되는 것 같아요~ 공통 함수로 처리해주면 어떨까요?

2021-05-23 16:54 UTC, Kihyun92 approved these changes
이번주도 고생 많으셨습니다~ DM 으로 많이 질문해주셔서 좋았습니다.

이번 과제를 진행하면서 무엇을 배우셨나요? 더 배워보고 싶은 부분이 있는지 정리해봐도 좋을 것 같습니다.

슬랙 채널에 회고 남겨주시면 확인후 머지하겠습니다~

2021-05-23 16:55 UTC, Kihyun92 commented
https://github.com/CodeSoom/react-week3-assignment-1/pull/76/checks?check_run_id=2650698153
CI를 통과하지 못하는 것 같은데, 확인 후 수정해주세요~

2021-05-31 15:41 UTC, merged