각 컴포넌트 테스트 파일 생성
CodeSoom/react-week3-assignment-1 pull request #78
Opened 2021-05-18 09:14 UTC by hanvit7

안녕하세요 트레이너님 리뷰요청드립니다.

처음 테스트코드란 것을 작성하다보니 어떤 식으로 해야하는지 좀 더 봐야할 것 같습니다. ㅎㅎ

상태에 대한 테스트는 변화하는 과정을 테스트 코드로 만들 필요는 없고 
변화된 상태의 값 만을 넣어서 테스트하는 것 같은데 맞게 이해 하고있는 것 인지요??

2021-05-18 16:15 UTC, Kihyun92 requested changes
> 상태에 대한 테스트는 변화하는 과정을 테스트 코드로 만들 필요는 없고
변화된 상태의 값 만을 넣어서 테스트하는 것 같은데 맞게 이해 하고있는 것 인지요??

말씀하신대로 상태에 따른 화면 노출 여부를 테스트해줘야합니다.

추가적으로 이벤트에 대한 테스트도 할 수 있겠네요. 투두 리스트는 상태에 따라 여러 버튼들이 존재합니다. 해당 버튼들에 대한 이벤트도 테스트해주면 좋을 것 같아요 :)

2021-05-18 16:15 UTC, Kihyun92 commented on src/App.test.jsx
> +  test('empty page', () => {
할일이 있는 경우에 대해서도 확인해주면 좋겠군요~

2021-05-18 16:15 UTC, Kihyun92 commented on src/List.test.jsx
> +  });
단순히 완료의 노출 유무만 테스트하는 것 보다 리스트가 여러개인 경우에 대해서도 고려되면 좋을 것 같아요.

2021-05-18 16:15 UTC, Kihyun92 commented on src/List.test.jsx
> +    ));
리스트를 렌더해주는 코드가 중복되고 있네요. 테스트 코드 또한 리팩터링의 대상입니다. 어떻게 개선할 수 있을까요?

2021-05-20 06:45 UTC, hanvit7 commented
List와 Input 컴포넌트 테스트 추가 하였습니다.
오늘 저녁에 나머지 컴포넌트도 테스트 추가할예정입니다.
리뷰 부탁드립니다.

2021-05-20 12:52 UTC, Kihyun92 requested changes
테스트를 잘 진행하고 계신 것 같습니다!

나머지 부분들에 대한 테스트도 기다리고 있겠습니다 😊

2021-05-20 12:52 UTC, Kihyun92 commented on src/Input.test.jsx
> +  expect(getByRole('textbox').value).toMatch('');
`추가` 버튼이 클릭됐을때 이벤트가 정상적으로 호출되는지도 확인하면 좋을 것 같네요~

2021-05-20 12:52 UTC, Kihyun92 commented on src/List.test.jsx
> +  });
할일이 있는 경우와 없는 경우에 대해서 각각 테스트 코드를 작성해보신 것 같아요~ 좋습니다 👍🏼 

추가적으로 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현해 볼 수 있습니다.

``` jest
describe('List', () => {
  context('할 일이 없는 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('할 일이 있는 경우', () => {
    ~~ 생략 ~~
```
위 예시를 차례대로 보면 `List는 할 일이 없는 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? ☺️

참고
- https://ko.javascript.info/testing-mocha
-  https://www.betterspecs.org/#contexts

2021-05-20 15:33 UTC, hanvit7 commented
트레이너님 리뷰 요청드립니다.
List 컴포넌트 테스트 릭팩토링 하였고 
Page 컴포넌트 테스트 추가하였습니다.
App 컴포넌트의 각 함수들을 테스트해야 할 것 같은데...여기서 막히네요...
App 컴포넌트에 전달할 props들도 없는데 안에 있는 함수를 App 컴포넌트를 가지고 테스트 하는게 맞는 것인지요..??
또 헤메고 오겠습니다. ㅎㅎ

2021-05-21 15:30 UTC, Kihyun92 requested changes
> App 컴포넌트의 각 함수들을 테스트해야 할 것 같은데...여기서 막히네요...
App 컴포넌트에 전달할 props들도 없는데 안에 있는 함수를 App 컴포넌트를 가지고 테스트 하는게 맞는 것인지요..??

꼭 props를 넘겨야만 테스트를 할 수 있는건 아닙니다. 
[react testing library](https://testing-library.com/docs/react-testing-library/intro/) 를 사용해서 가상으로 실제 유저가 동작하는 것 처럼, 해당 컴포넌트 내의 버튼을 누르거나 인풋을 입력하는 등 테스트해줄 수 있죠 ㅎㅎ

2021-05-21 15:30 UTC, Kihyun92 commented on src/List.test.jsx
> +      ));
리스트 컴포넌트를 render 하는 코드가 매 테스트마다 반복 되는 것 같아요. 이 부분을 함수로 추출하면 어떨까요?

2021-05-21 15:30 UTC, Kihyun92 commented on src/List.test.jsx
> +  context('할 일이 있는 경우', () => {
할일의 완료 버튼을 누르면 리스트가 바뀌는걸 테스트해줘도 좋을 것 같네요~

2021-05-23 05:53 UTC, hanvit7 commented
트레이너님 리뷰 요청드립니다.
각각의 컴포넌트의 관심사에 맞춰 테스트 하는 부분이 아직 조금 헷갈리지만 아는 선까지 해보았습니다.
컴포넌트 별로 테스트가 중복(완전히 같다고 보기도 어렵지만) 되는 건 당연한 것이겠죠??

2021-05-23 14:59 UTC, Kihyun92 requested changes
> 컴포넌트 별로 테스트가 중복(완전히 같다고 보기도 어렵지만) 되는 건 당연한 것이겠죠??

각 컴포넌트마다 가지고 있는 관심사의 수준이 다르기 때문에 하위 컴포넌트의 구현상세를 과도하게 테스트하게 될 수 있습니다. 이 경우 상위에서 너무 많은 걸 알고 있다는 신호고 이는 설계적으로 문제가 될 수 있어요. 다만 지금은 너무 깊게 고민 마시고, 극단적으로 테스트해보시고 느껴보시면 좋을 것 같아요 ㅎㅎ

2021-05-23 14:59 UTC, Kihyun92 commented on src/Input.test.jsx
> +    expect(getByPlaceholderText('할 일을 입력해 주세요')).toBeValid();
input 을 찾으실 때 getByLabelText 를 사용하시면 더 대상이 명확하게 드러날 것 같아요~

2021-05-23 14:59 UTC, Kihyun92 commented on src/Input.test.jsx
> +    fireEvent.change(getByLabelText('할 일'), {
change 시키기 이전에 테스트할 함수가 이전엔 호출되지 않았는지 확인해도 좋을 것 같아요~

2021-05-23 14:59 UTC, Kihyun92 commented on src/List.test.jsx
> +      expect(handleClickDelete).toBeCalled();
task를 추가로 확인해야하는 경우엔 계속 하단에 같은 로직을 추가해야할 것 같아요. 반복문을 사용해서 이 부분을 개선해줘도 좋을 것 같네요 :)

2021-05-23 15:00 UTC, Kihyun92 commented
이번주도 고생 많으셨습니다~ 과제 풀이 영상을 보시고, 아샬님은 어떻게 테스트를 구현하시는지 보시면 좋을 것 같아요 ㅎㅎ

이번 과제를 진행하면서 무엇을 배우셨나요? 더 배워보고 싶은 부분이 있는지 정리해봐도 좋을 것 같습니다.

슬랙 채널에 회고 남겨주시면 확인후 머지하겠습니다 :)

2021-05-31 15:43 UTC, merged