Todo test
CodeSoom/react-week3-assignment-1 pull request #79
Opened 2021-05-19 12:48 UTC by dngwoodo

좀 늦었습니다. 막상 해보려니 너무 어렵네요... 특히 Input 컴포넌트 부분에서 value를 바꿨을 때 어떻게 테스트해야될지 잘 모르겠습니다.
전에 TDD를 조금 공부할 때 정리해둔 https://github.com/dngwoodo/TIL/tree/master/TDD/velopert/React/rtl-tutorial
를 참고 했습니다

2021-05-19 15:15 UTC, Kihyun92 requested changes
> input 컴포넌트 부분에서 value를 바꿨을 때 어떻게 테스트해야될지 잘 모르겠습니다.

사용 설명서와 같은 관점에서 테스트 코드를 바라보고, 해당 컴포넌트를 사용하는 사람에게 예제로 테스트를 제공한다고 생각해보면 좋습니다. input 컴포넌트에서 무엇을 어떻게 보여주고 싶으신가요?

2021-05-19 15:15 UTC, Kihyun92 commented on src/Input.test.jsx
> +    screen.getByRole('button', { name: /추가/ });
render 함수에서 사용할 수 있는 것들이 있습니다. 참고해보시면 좋을 것 같아요~

참고:
- https://testing-library.com/docs/react-testing-library/api#render

2021-05-19 16:52 UTC, dngwoodo commented on src/Input.test.jsx
> +    screen.getByRole('button', { name: /추가/ });
피드백 감사합니다. 처음엔 아샬님 코드로 작성을 하다가 
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library 
켄트 백의 블로그를 읽고 수정을 하게 되었습니다. 

1. screen을 이용하라고 권장
2. expect를 굳이 쓰지 않아도  getByRole로 찾지못하면 테스트 실패

이렇게 두가지 이유로 이렇게 작성하게  되었습니다. 어떻게 작성하는게 좋을까요 ?

2021-05-19 16:55 UTC, dngwoodo commented
> > input 컴포넌트 부분에서 value를 바꿨을 때 어떻게 테스트해야될지 잘 모르겠습니다.
> 
> 사용 설명서와 같은 관점에서 테스트 코드를 바라보고, 해당 컴포넌트를 사용하는 사람에게 예제로 테스트를 제공한다고 생각해보면 좋습니다. input 컴포넌트에서 무엇을 어떻게 보여주고 싶으신가요?

UI만을 담당하는 컴포넌트이기 때문에 우선 UI 테스트와 이벤트들이 발생되었을 때 이벤트 핸들러가  제대로 실행되는지 보여주면 될 것 같습니다.

1. UI 테스트 (인풋, 버튼이 화면에 제대로 출력 되는지)
2. value가 바뀌었을 경우 onChange가 호출되는지
3. 버튼이 클릭되었을 경우 onClick이 호출되는지

2021-05-19 16:57 UTC, dngwoodo commented
> > > input 컴포넌트 부분에서 value를 바꿨을 때 어떻게 테스트해야될지 잘 모르겠습니다.
> > 
> > 
> > 사용 설명서와 같은 관점에서 테스트 코드를 바라보고, 해당 컴포넌트를 사용하는 사람에게 예제로 테스트를 제공한다고 생각해보면 좋습니다. input 컴포넌트에서 무엇을 어떻게 보여주고 싶으신가요?
> 
> UI만을 담당하는 컴포넌트이기 때문에 우선 UI 테스트와 이벤트들이 발생되었을 때 이벤트 핸들러가 제대로 실행되는지 보여주면 될 것 같습니다.
> 
> 1. UI 테스트 (인풋, 버튼이 화면에 제대로 출력 되는지)
> 2. value가 바뀌었을 경우 onChange가 호출되는지
> 3. 버튼이 클릭되었을 경우 onClick이 호출되는지

2021-05-19 17:00 UTC, dngwoodo commented
https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/36f7a483cbfef0be45502480f6eff589e25e6b60
이 커밋에서 삭제한 테스트케이스는 지우는게 맞는지 아직 잘모르겠습니다.. tasks에 따라 화면에 보여지는 게 다르기 때문에 그 부분들은 테스트를 시도했는데 value도 바뀜에 따라 화면에 보여지는 것이 다르니 이 부분도 테스트를 해야 맞지 않나 생각이 됩니다. 피드백 부탁드리겠습니다

2021-05-20 13:28 UTC, Kihyun92 commented on src/Input.test.jsx
> +    screen.getByRole('button', { name: /추가/ });
상황마다 다를 것 같아요 :)

개인적으로는 필요한 걸 적절하게 가져다 쓰는걸 선호해서 구조분해할당을 통해 사용할 쿼리만 가져와 씁니다.

screen 을 이용하면 보다 편한 장점이 있죠 ㅎㅎ

그리고 `getBy*`만으로도 해당 요소를 찾지 못하면 에러가 발생해서 충분히 테스트 가능하지만, `assert` 문으로 작성한다면 `의도`를 더 분명히 할 수 있을 것 같아요~

ex) `expect(getByText('할 일이 없어요!')).not.toBeNull();`

2021-05-20 13:30 UTC, Kihyun92 commented
> [36f7a48](https://github.com/CodeSoom/react-week3-assignment-1/commit/36f7a483cbfef0be45502480f6eff589e25e6b60)
> 이 커밋에서 삭제한 테스트케이스는 지우는게 맞는지 아직 잘모르겠습니다. tasks에 따라 화면에 보여지는 게 다르기 때문에 그 부분들은 테스트를 시도했는데 value도 바뀜에 따라 화면에 보여지는 것이 다르니 이 부분도 테스트를 해야 맞지 않나 생각이 됩니다. 피드백 부탁드리겠습니다

해당 테스트를 왜 제거하게 되었나요?

2021-05-20 13:42 UTC, Kihyun92 requested changes
전반적으로 테스트를 잘 진행해주고 계시네요 👍🏼 

테스트 코드도 리팩터링 대상입니다. 반복되는 비슷한 로직을 어떻게 개선할 수 있을지 고민해보시면 좋을 것 같아요 :)

2021-05-20 13:42 UTC, Kihyun92 commented on src/Input.test.jsx
> +    fireEvent.change(input, { target: { value: '뭐라도 하기' } });
`input` 을 찾으실 때 `getByLabelText` 를 사용하시면 더 대상이 명확하게 드러날 것 같아요.

2021-05-20 13:42 UTC, Kihyun92 commented on src/Input.test.jsx
> +    render(<Input onClick={onClick} />);
렌더해주는 코드가 비슷하게 반복 되는것 같아요. 테스트에서 반복을 줄이는 방법은 없을까요?

2021-05-20 13:42 UTC, Kihyun92 commented on src/List.test.jsx
> +    screen.getByText(tasks[1].title);
지금은 확인하는 task가 두개밖에 없지만, task를 추가로 확인해야하는 경우엔 계속 하단에 같은 로직이 추가될 것 같아요.

tasks를 이용해 반복되는 로직을 처리할 방법이 있을까요?

2021-05-20 13:42 UTC, Kihyun92 commented on src/List.test.jsx
> +  it('renders tasks', () => {
할일이 있는 경우와 없는 경우에 대해서 각각 테스트 코드를 작성해보신 것 같군요 👍🏼 

추가적으로 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현해 볼 수 있습니다.

``` jest
describe('List', () => {
  context('할 일이 없는 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('할 일이 있는 경우', () => {
    ~~ 생략 ~~
```
위 예시를 차례대로 보면 `List는 할 일이 없는 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? ☺️

참고
- https://ko.javascript.info/testing-mocha
-  https://www.betterspecs.org/#contexts

2021-05-20 16:28 UTC, dngwoodo commented on src/Input.test.jsx
> +    screen.getByRole('button', { name: /추가/ });
피드백 감사합니다. 수정해보겠습니다!

2021-05-20 16:30 UTC, dngwoodo commented
> > [36f7a48](https://github.com/CodeSoom/react-week3-assignment-1/commit/36f7a483cbfef0be45502480f6eff589e25e6b60)
> > 이 커밋에서 삭제한 테스트케이스는 지우는게 맞는지 아직 잘모르겠습니다. tasks에 따라 화면에 보여지는 게 다르기 때문에 그 부분들은 테스트를 시도했는데 value도 바뀜에 따라 화면에 보여지는 것이 다르니 이 부분도 테스트를 해야 맞지 않나 생각이 됩니다. 피드백 부탁드리겠습니다
> 
> 해당 테스트를 왜 제거하게 되었나요?

우선 해당 테스트가 제대로 동작하지 않아서 삭제하게 되었습니다. value를 바꿔도 Received: "" 이렇게 바뀌지 않고 고정이 되어있어서 지우게 되었습니다 ㅠ

2021-05-21 10:35 UTC, dngwoodo commented on src/Input.test.jsx
> +    fireEvent.change(input, { target: { value: '뭐라도 하기' } });
피드백 감사합니다.
https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/8a2acea6d1c5cc59baf4081af4a62a282f125d6f
에서 수정했습니다.

2021-05-21 12:17 UTC, dngwoodo commented on src/Input.test.jsx
> +    render(<Input onClick={onClick} />);
피드백 감사합니다! https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/ebe39eb0afe033039df5f373c2a6f28d37bbe13b에서 변경해주었습니다. 잘 했는 지는 잘 모르겠습니다

2021-05-21 12:18 UTC, dngwoodo commented on src/List.test.jsx
> +    screen.getByText(tasks[1].title);
https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/6474982fb0b613d62704c361c5a1ffa9ca2869f8 에서 변경해주었습니다. for문을 사용해서 처리해줬습니다. 커밋 내용도 한번 봐주시면 감사하겠습니다.

2021-05-21 12:32 UTC, dngwoodo commented on src/List.test.jsx
> +  it('renders tasks', () => {
피드백 감사합니다. https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/24c0459896525c9223d47c18bf4030fc9a6db052 에서 변경했습니다. context로 나눠주니 task가 있을 때와 없을 때 좀 더 명료하게 테스트가 가능한 것 같습니다. 글을 적다보니 생각 난건데 context에 상관없이 test를 해야되는 경우는 context 바깥으로 빼야겠네요 . Page 컴포넌트에서 task는 다르지만 같은 테스트를 두곳에 다 넣어줬습니다. 

커밋 내용도 한번 봐주세요!

2021-05-21 12:37 UTC, dngwoodo commented on src/List.test.jsx
> +  it('renders tasks', () => {
https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/d654baaa039a717629d78e6e0e479650d9ae331a 에서 추가적으로 변경했습니다.

2021-05-21 16:02 UTC, Kihyun92 commented
> > > [36f7a48](https://github.com/CodeSoom/react-week3-assignment-1/commit/36f7a483cbfef0be45502480f6eff589e25e6b60)
> > > 이 커밋에서 삭제한 테스트케이스는 지우는게 맞는지 아직 잘모르겠습니다. tasks에 따라 화면에 보여지는 게 다르기 때문에 그 부분들은 테스트를 시도했는데 value도 바뀜에 따라 화면에 보여지는 것이 다르니 이 부분도 테스트를 해야 맞지 않나 생각이 됩니다. 피드백 부탁드리겠습니다
> > 
> > 
> > 해당 테스트를 왜 제거하게 되었나요?
> 
> 우선 해당 테스트가 제대로 동작하지 않아서 삭제하게 되었습니다. value를 바꿔도 Received: "" 이렇게 바뀌지 않고 고정이 되어있어서 지우게 되었습니다. 피드백 주시면 감사하겠습니다.
> 
> 한가지 더 질문이 있습니다. 제가 지금 커밋을 한개 실수해서 reset HEAD~1로 되돌리고 커밋을 다시 한 다음 git push origin todo-test를 하니 rejected 되서 -f 를 이용해서 강제로 넣어주었는데요. 이런 상황에선 보통 어떻게 처리하는 게 좋을까요?

render(<Page value={taskTitle} tasks={emptyTasks} />);

2021-05-21 16:22 UTC, Kihyun92 requested changes
리뷰 드린것 보다 더 잘 반영해주시는 것 같아요! 👍🏼 

커밋 내용과 수정 내역들을 보니 `forEach` 를 사용하는 부분도 적절하고, `describe-context-it` 도 잘 이해하신 것 같습니다.

의논거리가 있다면 지금처럼 적극적으로 말씀해주세요 😊

2021-05-21 16:22 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    render(<Input {...props} />);
spreading 해주지 않고 실제 컴포넌트를 사용하는 것처럼 props를 넘겨주면 어떨까요?

2021-05-21 16:22 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    const onChange = jest.fn();
함수들을 mocking 하는 부분을 setup 함수에 추가하는건 어떤가요?

2021-05-21 16:22 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    expect(onClick).toBeCalled();
이전에 진짜로 호출되지 않았는지 확인해주는 코드가 필요할 것 같아요.

2021-05-21 16:22 UTC, Kihyun92 commented on src/test/components/List.test.jsx
> +    it('renders text', () => {
context 를 잘 사용해주셨군요! 👍🏼 

단순히 `renders text` 보단, 테스트만 보고도 어떤 텍스트가 노출되는지 알수 있도록 해줘도 좋을 것 같아요.

2021-05-21 16:22 UTC, Kihyun92 commented on src/test/components/Page.test.jsx
> +    it('renders title, Input, List', () => {
`할 일이 없어요` 도 노출한다는걸 알려줘도 좋겠네요 :)

2021-05-21 16:22 UTC, Kihyun92 commented on src/test/components/Page.test.jsx
> +  });
이 테스트들도 결국 tasks 가 있는 경우이기 때문에 `'when exist tasks' context` 안에 있어도 되지 않을까요?

2021-05-21 17:46 UTC, dngwoodo commented on src/test/components/Input.test.jsx
> +    const onChange = jest.fn();
이 부분은 잘 모르겠습니다. setup({ onChange }) 이렇게 어떤 props를 줄 지 명시적으로 해주는게 더 좋을 것 같습니다.
만약 바깥으로 뺀다면 describe 최상위 스코프에 추가해주는게 맞지 않나 싶습니다.

만약 바꾼다면 이렇게 해줄 수 있을까요?

```jsx
  function setup(props = {
    value: undefined,
  }) {
    const { value } = props;
    const onChange = jest.fn();

   const onClick = jest.fn();

    // eslint-disable-next-line react/jsx-props-no-spreading
    render(
      <Input
        value={value}
        onChange={onChange}
        onClick={onClick}
      />,
    );
  }
```

2021-05-21 17:59 UTC, dngwoodo commented on src/test/components/Page.test.jsx
> +  });
저도 이 부분을 고민을 해봤는데 tasks가 있던 없던 무조건 실행되야 되는 코드들이라 context 바깥으로 빼주었습니다. 트레이너님은 어떻게 하는게 좋아보이시나요 ?

2021-05-21 18:03 UTC, dngwoodo commented
> > > > [36f7a48](https://github.com/CodeSoom/react-week3-assignment-1/commit/36f7a483cbfef0be45502480f6eff589e25e6b60)
> > > > 이 커밋에서 삭제한 테스트케이스는 지우는게 맞는지 아직 잘모르겠습니다. tasks에 따라 화면에 보여지는 게 다르기 때문에 그 부분들은 테스트를 시도했는데 value도 바뀜에 따라 화면에 보여지는 것이 다르니 이 부분도 테스트를 해야 맞지 않나 생각이 됩니다. 피드백 부탁드리겠습니다
> > > 
> > > 
> > > 해당 테스트를 왜 제거하게 되었나요?
> > 
> > 
> > 우선 해당 테스트가 제대로 동작하지 않아서 삭제하게 되었습니다. value를 바꿔도 Received: "" 이렇게 바뀌지 않고 고정이 되어있어서 지우게 되었습니다. 피드백 주시면 감사하겠습니다.
> > 한가지 더 질문이 있습니다. 제가 지금 커밋을 한개 실수해서 reset HEAD~1로 되돌리고 커밋을 다시 한 다음 git push origin todo-test를 하니 rejected 되서 -f 를 이용해서 강제로 넣어주었는데요. 이런 상황에선 보통 어떻게 처리하는 게 좋을까요?
> 
> `render(<Page value={taskTitle} tasks={emptyTasks} />);` 이렇게 사용하신 것 같아요.
> Page 컴포넌트에는 아래와 같이 taskTitle로 넘겨야하지 않나요?
> `render(<Page taskTitle={taskTitle} tasks={emptyTasks} />);`
> 
> 아래 질문은 rejected 됐을때의 에러 메시지를 알아야 제대로된 답변을 드릴 수 있을 것 같아요. 그리고 혹시 reset 시에는 다른 커맨드는 사용하지 않았나요? 올바르게 리셋이 됐다면, 올바르게 푸쉬 되는게 맞을 것 같습니다.

https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/9cec6d9a072b7d19e38208c5d8ca914879080a5a 에서 테스트 추가했습니다. 실수해놓고 안된다고 하고 있었군요 ㅋㅋㅋ 죄송합니다 

push 부분은 제가 설명이 부족했던 것 같습니다. rejected 된 이유는 이미 git push origin todo-test를 하고나서 git reset 을 했기 때문에 커밋이 달라져서 rejected 되었습니다. 이럴 경우에 그냥 --force 하는게 정답일까요?

2021-05-21 18:04 UTC, dngwoodo commented on src/test/components/Input.test.jsx
> +    render(<Input {...props} />);
https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/0b6b3988277f8833cb4c1a0c015035ac5773bf8e 에서 수정했습니다. Typescript의 optional이 생각나서 기본 값을 undefined로 해주었습니다. 이 부분은 피드백 부탁드리겠습니다!

2021-05-21 18:06 UTC, dngwoodo commented on src/test/components/Input.test.jsx
> +    expect(onClick).toBeCalled();
피드백 감사합니다. https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/bb3b01cac35b520b81b0af07b6888d2792a23c6f 에서 수정했습니다.

2021-05-21 18:06 UTC, dngwoodo commented on src/test/components/List.test.jsx
> +    it('renders text', () => {
피드백 감사합니다! https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/76f6bb8fc99b44de1891138b45261a55bd0c6edb 에서 수정했습니다.

2021-05-21 18:06 UTC, dngwoodo commented on src/test/components/Page.test.jsx
> +    it('renders title, Input, List', () => {
피드백 감사합니다! https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/76f6bb8fc99b44de1891138b45261a55bd0c6edb 에서 수정했습니다.

2021-05-22 14:30 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    const onChange = jest.fn();
앗 이 부분은 제가 잘못 남겼었네요.. 죄송합니다 😅

말씀하신대로 `describe` 아래 즉, 테스트 상단에 함수들을 mocking 하면 어떨까요?

`Input` 컴포넌트를 렌더할때, `onClick, onChange` 함수의 경우엔 옵셔널 값이 아닐 것 같습니다.

2021-05-22 14:32 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    render(<Input {...props} />);
type과 인자가 있을 경우와 없을 경우를 고려하셔서 작업해주셨군요 👍🏼 

2번에 대해서 조금 더 고려해보면 좋을 것 같아요. 우리는 Input 컴포넌트에 `value, onChange, onClick` 을 넘겨주고 있습니다. 
value의 경우엔 말씀하신대로 optional 일 것 같아요. 하지만 onChange, onClick의 경우에는 항상 넘겨줘야하는 함수들인 것 같아요.

항상 넘겨줘야하는 함수를 굳이 인자로 넘겨줄 필요가 없을 것 같아요. ([다른 커멘트 참조](https://github.com/CodeSoom/react-week3-assignment-1/pull/79#discussion_r637410787))

그럼 value 만 setup 함수에 넘겨주면 되는데, 인자가 하나인 경우에 굳이 객체로 넘길 필요 없이 `setup(value)`와 같이 해줄 수 있겠네요. 어떤가요?

2021-05-22 14:34 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    expect(onClick).toBeCalled();
버튼이 존재하는지 추가해주셨군요!ㅎㅎ 이것도 좋습니다.

제 의도는 `expect(onClick).toBeCalled();`를 추가하는건 어떨지 였어요 :)

2021-05-22 14:36 UTC, Kihyun92 commented on src/test/components/Page.test.jsx
> +  });
아 그렇군요! 동우님 의도대로 처리해도 좋을 것 같습니다 :)

2021-05-22 14:46 UTC, Kihyun92 commented
> > > > > [36f7a48](https://github.com/CodeSoom/react-week3-assignment-1/commit/36f7a483cbfef0be45502480f6eff589e25e6b60)
> > > > > 이 커밋에서 삭제한 테스트케이스는 지우는게 맞는지 아직 잘모르겠습니다. tasks에 따라 화면에 보여지는 게 다르기 때문에 그 부분들은 테스트를 시도했는데 value도 바뀜에 따라 화면에 보여지는 것이 다르니 이 부분도 테스트를 해야 맞지 않나 생각이 됩니다. 피드백 부탁드리겠습니다
> > > > 
> > > > 
> > > > 해당 테스트를 왜 제거하게 되었나요?
> > > 
> > > 
> > > 우선 해당 테스트가 제대로 동작하지 않아서 삭제하게 되었습니다. value를 바꿔도 Received: "" 이렇게 바뀌지 않고 고정이 되어있어서 지우게 되었습니다. 피드백 주시면 감사하겠습니다.
> > > 한가지 더 질문이 있습니다. 제가 지금 커밋을 한개 실수해서 reset HEAD~1로 되돌리고 커밋을 다시 한 다음 git push origin todo-test를 하니 rejected 되서 -f 를 이용해서 강제로 넣어주었는데요. 이런 상황에선 보통 어떻게 처리하는 게 좋을까요?
> > 
> > 
> > `render(<Page value={taskTitle} tasks={emptyTasks} />);` 이렇게 사용하신 것 같아요.
> > Page 컴포넌트에는 아래와 같이 taskTitle로 넘겨야하지 않나요?
> > `render(<Page taskTitle={taskTitle} tasks={emptyTasks} />);`
> > 아래 질문은 rejected 됐을때의 에러 메시지를 알아야 제대로된 답변을 드릴 수 있을 것 같아요. 그리고 혹시 reset 시에는 다른 커맨드는 사용하지 않았나요? 올바르게 리셋이 됐다면, 올바르게 푸쉬 되는게 맞을 것 같습니다.
> 
> [9cec6d9](https://github.com/CodeSoom/react-week3-assignment-1/commit/9cec6d9a072b7d19e38208c5d8ca914879080a5a) 에서 테스트 추가했습니다. 실수해놓고 안된다고 하고 있었군요 ㅋㅋㅋ 죄송합니다
> 
> push 부분은 제가 설명이 부족했던 것 같습니다. rejected 된 이유는 이미 git push origin todo-test를 하고나서 git reset 을 했기 때문에 커밋이 달라져서 rejected 되었습니다. 이럴 경우에 그냥 --force 하는게 정답일까요?

아 이미 푸시한 뒤에 리셋을 한 경우군요. 이 경우에는 말씀하신대로 force push 하는 방법과 revert 한 뒤 push 하는 방법이 있습니다.

전자의 경우엔 혼자 작업할때, 즉 본인이 잘못 푸시한 걸 동료가 pull 받지 않는 경우에 사용할 수 있어요. 그 외에는 revert 를 사용한 방법을 사용하시면 됩니다. ㅎㅎ

참고: 
- https://stackoverflow.com/questions/1463340/how-to-revert-multiple-git-commits

2021-05-22 14:49 UTC, Kihyun92 requested changes
커맨트 확인해보시고 의논이 필요하면 말씀해주세요~

과제 풀이 영상을 보시고 아샬님은 어떻게 테스트를 접근하시는지 보셔도 좋을 것 같습니다 :)

2021-05-22 14:49 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    // eslint-disable-next-line react/jsx-props-no-spreading
이제 스프레드 연산자를 사용하지 않으니 제거해도 될 것 같아요~

2021-05-22 15:36 UTC, dngwoodo commented on src/test/components/Input.test.jsx
> +    expect(onClick).toBeCalled();
```jsx
expect(onClick).toBeCalled();
```
엇 이 부분은 이미 존재하고 있었습니다.  생각해보니 테스트 케이스가 onClick이 호출되었는지이기 때문에 따로 버튼이 존재하는지는 테스트 를 추가해주지 않아도 괜찮았을 것 같습니다!

2021-05-22 16:20 UTC, dngwoodo commented on src/test/components/Input.test.jsx
> +    // eslint-disable-next-line react/jsx-props-no-spreading
피드백 감사합니다! https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/06eb9f70cd7f99b6fe7e0291d2decf4a03ee05a1 에서 수정했습니다.

2021-05-22 16:20 UTC, dngwoodo commented
> > > > > > [36f7a48](https://github.com/CodeSoom/react-week3-assignment-1/commit/36f7a483cbfef0be45502480f6eff589e25e6b60)
> > > > > > 이 커밋에서 삭제한 테스트케이스는 지우는게 맞는지 아직 잘모르겠습니다. tasks에 따라 화면에 보여지는 게 다르기 때문에 그 부분들은 테스트를 시도했는데 value도 바뀜에 따라 화면에 보여지는 것이 다르니 이 부분도 테스트를 해야 맞지 않나 생각이 됩니다. 피드백 부탁드리겠습니다
> > > > > 
> > > > > 
> > > > > 해당 테스트를 왜 제거하게 되었나요?
> > > > 
> > > > 
> > > > 우선 해당 테스트가 제대로 동작하지 않아서 삭제하게 되었습니다. value를 바꿔도 Received: "" 이렇게 바뀌지 않고 고정이 되어있어서 지우게 되었습니다. 피드백 주시면 감사하겠습니다.
> > > > 한가지 더 질문이 있습니다. 제가 지금 커밋을 한개 실수해서 reset HEAD~1로 되돌리고 커밋을 다시 한 다음 git push origin todo-test를 하니 rejected 되서 -f 를 이용해서 강제로 넣어주었는데요. 이런 상황에선 보통 어떻게 처리하는 게 좋을까요?
> > > 
> > > 
> > > `render(<Page value={taskTitle} tasks={emptyTasks} />);` 이렇게 사용하신 것 같아요.
> > > Page 컴포넌트에는 아래와 같이 taskTitle로 넘겨야하지 않나요?
> > > `render(<Page taskTitle={taskTitle} tasks={emptyTasks} />);`
> > > 아래 질문은 rejected 됐을때의 에러 메시지를 알아야 제대로된 답변을 드릴 수 있을 것 같아요. 그리고 혹시 reset 시에는 다른 커맨드는 사용하지 않았나요? 올바르게 리셋이 됐다면, 올바르게 푸쉬 되는게 맞을 것 같습니다.
> > 
> > 
> > [9cec6d9](https://github.com/CodeSoom/react-week3-assignment-1/commit/9cec6d9a072b7d19e38208c5d8ca914879080a5a) 에서 테스트 추가했습니다. 실수해놓고 안된다고 하고 있었군요 ㅋㅋㅋ 죄송합니다
> > push 부분은 제가 설명이 부족했던 것 같습니다. rejected 된 이유는 이미 git push origin todo-test를 하고나서 git reset 을 했기 때문에 커밋이 달라져서 rejected 되었습니다. 이럴 경우에 그냥 --force 하는게 정답일까요?
> 
> 아 이미 푸시한 뒤에 리셋을 한 경우군요. 이 경우에는 말씀하신대로 force push 하는 방법과 revert 한 뒤 push 하는 방법이 있습니다.
> 
> 전자의 경우엔 혼자 작업할때, 즉 본인이 잘못 푸시한 걸 동료가 pull 받지 않는 경우에 사용할 수 있어요. 그 외에는 revert 를 사용한 방법을 사용하시면 됩니다. ㅎㅎ
> 
> 참고:
> 
> * https://stackoverflow.com/questions/1463340/how-to-revert-multiple-git-commits

답변 감사합니다. 협업시에는 revert로 커밋을 남겨야 되나보군요!

2021-05-22 16:23 UTC, dngwoodo commented on src/test/components/Input.test.jsx
> +    render(<Input {...props} />);
피드백 감사합니다. https://github.com/CodeSoom/react-week3-assignment-1/pull/79/commits/9bb9235f808db35e7a728c10c40c6e7e5547b231 에서 수정했습니다. 인자를 한개만 주게 되면 초기 값을 안주게 되면 undefined로 설정되기 때문에 굳이 null로 값을 줄 필요가 있을까요 ??

커밋 부분에 대한 피드백 부탁드리겠습니다!

2021-05-22 16:28 UTC, dngwoodo commented
마지막까지 질문을 남기게 되었습니다 ㅎㅎ..

질문 1: https://github.com/CodeSoom/react-week3-assignment-1/pull/79#discussion_r637422686
질문 2: https://github.com/CodeSoom/react-week3-assignment-1/pull/79#discussion_r637417861

이번주 리뷰 꼼꼼히 해주셔서 감사합니다!

2021-05-23 15:18 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    render(<Input {...props} />);
> 1. 인자를 한개만 주게 되면 초기 값을 안주게 되면 undefined로 설정되기 때문에 굳이 null로 값을 줄 필요가 있을까요 ?

큰 이유는 없어요 😅  undefined 보단 null 을 넣어주고 싶어서 그랬는데, 지금의 경우엔 굳이 값을 넣어주지 않아도 될 것 같네요 ㅎㅎ

> 2. 인자를 두개 이상일 경우에는 객체로 넘겨주었습니다.

👍🏼  본인만의 기준이 있으면 좋습니다. 개인적으로는 두세개가 적당한 것 같아요 ㅎㅎ

> 3. onClick과 onChange를 모든 테스트에서 사용하는 것이 아닌데 무조건 setup에서 기본셋팅으로 넘겨줘야 할 필요가 있나요 ?

모든 테스트에서 사용하진 않지만, Input 컴포넌트에 대한 설명서의 관점에서라면 필요한 부분이라고 생각했습니다. 실제 사용할때 Input 컴포넌트에 해당 함수들이 optional하게 넘어오진 않으니까요.

2021-05-23 15:20 UTC, Kihyun92 commented on src/test/components/Input.test.jsx
> +    expect(onClick).toBeCalled();
헛 이것도 잘못 남겼었군요 ;;🙇🏻

`expect(onClick).not.toBeCalled()`를 의도했었습니다.

2021-05-23 15:21 UTC, Kihyun92 commented
> 마지막까지 질문을 남기게 되었습니다 ㅎㅎ..
> 
> 질문 1: [#79 (comment)](https://github.com/CodeSoom/react-week3-assignment-1/pull/79#discussion_r637422686)
> 질문 2: [#79 (comment)](https://github.com/CodeSoom/react-week3-assignment-1/pull/79#discussion_r637417861)
> 
> 이번주 리뷰 꼼꼼히 해주셔서 감사합니다!

이어서 커맨트 남겼습니다~ 많은 질문을 해주셔서 감사해요 😁

2021-05-23 15:22 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~

과제 풀이 영상을 보시고, 아샬님은 어떤 방식으로 테스트에 접근하시는지 보시면 좋을 것 같아요~

이번 과제를 진행하면서 무엇을 배우셨나요? 더 배워보고 싶은 부분이 있는지 정리해봐도 좋을 것 같습니다.

슬랙 채널에 회고 남겨주시면 확인후 머지하겠습니다 :)

2021-05-31 15:43 UTC, merged